open-power/op-build

openpower/package/habanero-xml/habanero-xml.mk, openpower/package/hostboot/hostboot-0001-Revert-Base-devtree-model-on-vpd.patch, openpower/package/hostboot/hostboot-0002-Changes-for-Habanero-bringup-uart-delay-and-centaur.patch, openpower/package/hostboot/hostboot-0003-Temporary-Patch-to-fix-PCIE-issues-for-Open-Power-sy.patch, openpower/package/hostboot/hostboot.mk, openpower/package/occ/occ.mk, openpower/package/openpower-pnor/openpower-pnor.mk, openpower/package/palmetto-xml/palmetto-xml.mk
Updates for buildroot, Hostboot, OCC, Palmetto-XML, and Habanero-XML packages.
=> Update Various Package Levels for Habanero

openpower/package/habanero-xml/habanero-xml.mk, openpower/package/hostboot/hostboot-0006-Serverwiz2-scripts.patch, openpower/package/palmetto-xml/palmetto-xml.mk
Changes to makefiles for habanero and palmetto xml, and hostboot patch that has the necessary scripts.
=> Serverwiz2 support for op-build

README
Hi, this a series of little updates to the build docs on Fedora.
=> updates for build docs on Fedora

openpower/package/occ/occ.mk
New OCC version for op-build.  Update to occ.mk.
=> New OCC version for op-build.

openpower/package/hostboot/hostboot-0012-Cap-off-the-TRACFBIN-such-that-nothing-exceeds-64-by.patch, openpower/package/hostboot/hostboot-0017-Fix-I2C-Reset-to-resolve-I2C-Bus-Arbitration-Lost-Er.patch, openpower/package/hostboot/hostboot-0018-Fix-constant-refresh-of-vpd-cache.patch
Contents Include:
- Update to Cap off TRACFBIN Patch
- Fix to resolve I2C Bus Arbitration Loss
- Fix to resolve constant refresh of VPD Cache
=> Include Must-Fix Hostboot Items for 1.1 Release

openpower/package/firestone-xml/firestone.mk, openpower/package/hostboot/hostboot-0019-Fix-TX_MSBSWAP-attribute-for-Firestone.patch, openpower/package/hostboot/hostboot-0020-Move-slave-sbe-start-before-proc-cen-ref-clk-enable.patch
Two patches and a firestone XML update needed for Firestone.
=> Update firestone XML and patches needed for Firestone

openpower/package/skiboot/skiboot.mk
=> Update skiboot to skiboot-5.0-rc3

openpower/package/occ/occ.mk
=> OCC firmware update for Habanero SoftLayer delivery.

openpower/configs/firestone_defconfig, openpower/configs/habanero_defconfig, openpower/package/openpower-pnor/Config.in, openpower/package/openpower-pnor/openpower-pnor.mk
=> create 32M habanero_update.pnor image for HPM updates

openpower/package/occ/occ.mk
=> OCC firmware update for Firestone

openpower/configs/hostboot/firestone.config, openpower/configs/hostboot/habanero.config, openpower/configs/hostboot/palmetto.config
-Set BMC_AST2400 in config files to enable serial console
and to enable SIO boot config functions
RTC:118752
=> Update palmetto/habanero/firestone config flags.

openpower/package/hostboot/hostboot-0008-Fix-PCIe-swap-issue.txt
This will take over https://github.com/open-power/op-build/pull/154
Note, commit numbers match hostboot commit.
=> Fix PCIe swap issue in processMRW.pl

openpower/package/skiboot/skiboot.mk
=> Bump skiboot to 5.0.2

openpower/package/hostboot/hostboot.mk
updated hostboot version to 4d1c59f09b6b0ab9236aa42694cb2e42cbe8d3eb
Tested on palmetto, habanero and firestone.
=> op-build hostboot package update June 23th

openpower/package/occ/occ.mk
Relevant changes on this OCC build:
- Added debug traces for APSS layout information
- OCC compilation using gcc4.9
=> Push OCC build level op_occ_150716a

openpower/configs/garrison_defconfig
Fixes https://github.com/open-power/op-build/issues/216
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
=> configs: Update garrison to use a le build

openpower/package/garrison-xml/garrison.mk
Updating Garrison-xml pointer to pick up cherckerboard mode and APSS channel setting updates.
=> Garrison-xml Pointer Update

openpower/package/hostboot/hostboot.mk
Updated hostboot version.  Tested on habanero, palmetto, and firestone HW.
=> op-build update August 11th

openpower/configs/hostboot/firestone.config, openpower/configs/hostboot/habanero.config, openpower/configs/hostboot/palmetto.config, openpower/package/hostboot/hostboot.mk
Updated hostboot version. Tested on habanero, palmetto, and firestone
HW.
=> op-build update August 12th

openpower/package/garrison-xml/garrison.mk
Picking up MSS_INTERLEAVE_ENABLE move and GPU_SENSE updates.
=> Update garrison-xml Pointer

openpower/package/hostboot/hostboot.mk
Updated hostboot version. Tested on habanero, palmetto, and firestone
HW only.
=> op-build update August 18th

openpower/package/hostboot/hostboot.mk
Updated versions: hostboot
Tested on habanero, palmetto, and firestone HW.  Garrison build only.
=> op-build update Sep 2nd

openpower/package/hostboot/hostboot.mk
Updated versions: hostboot
Tested on habanero, palmetto, and firestone HW.  Garrison build only.
=> op-build update Sep 3rd

openpower/package/skiboot/skiboot.mk
See https://github.com/open-power/skiboot/blob/skiboot-5.1.2/doc/release-notes/skiboot-5.1.2.txt for release notes
=> Bump skiboot to 5.1.2

openpower/package/habanero-xml/habanero-xml.mk, openpower/package/hostboot/hostboot.mk
Updated versions: hostboot, habanero-xml
Tested on palmetto, habanero, and firestone HW.  Garrison build only
=> op-build update Sep 11th

openpower/package/hostboot/hostboot-0004-SBE-update-support-for-adjusted-nest-freq.patch, openpower/package/hostboot/hostboot-0005-Function-to-set-nest-freq-based-off-dimms.patch, openpower/package/occ/occ.mk
=> OCC firmware update to support wof

openpower/package/firestone-xml/firestone.mk, openpower/package/hostboot/hostboot.mk
Updated versions: hostboot, and firestone-xml
Tested (boot to Petitboot only), palmetto, habanero, and firstone HW.
=> op-build update Sep 23rd

openpower/package/hostboot/hostboot.mk
Updated version: hostboot
Tested (boot to Petitboot only) habanero, and firstone HW
=> op-build update Sep 30th

openpower/package/skiboot/skiboot.mk
Release notes: https://github.com/open-power/skiboot/blob/f54aba63a94cd7d4f5ea58ca86726a8c93c19c6c/doc/release-notes/skiboot-5.1.5.txt
=> Bump skiboot to 5.1.5

openpower/package/hostboot/hostboot.mk
Updated version: hostboot
Tested (boot to Petitboot only) palmetto, habanero, and firstone HW
=> op-build update Oct 6th

openpower/package/skiboot/skiboot.mk
=> Bump skiboot to 5.1.6

openpower/package/occ/occ.mk
-Added gerrit change-id to most recent occ build commit
=> Update correct change-id for most recent build

openpower/package/skiboot/skiboot.mk
https://github.com/open-power/skiboot/blob/be37433aac780e06b159c6b16712db4f64ed7abc/doc/release-notes/skiboot-5.1.7.txt
https://github.com/open-power/skiboot/blob/be37433aac780e06b159c6b16712db4f64ed7abc/doc/release-notes/skiboot-5.1.8.txt
Not a lot of changes, just some bug fixes.
=> Bump skiboot to 5.1.8

openpower/package/firestone-xml/firestone.mk, openpower/package/garrison-xml/garrison.mk, openpower/package/hostboot/hostboot.mk
Updated versions: hostboot, firestone-xml, garrison-xml
Tested on: palmetto, habanero, and firestone (boot to Petitboot only)
=> op-build update Oct 20th

openpower/package/firestone-xml/firestone.mk, openpower/package/hostboot/hostboot.mk, openpower/package/palmetto-xml/palmetto-xml.mk
Updated versions: hostboot, firestone-xml, and palmetto-xml
Tested on HW (boot to Petitboot)
=> op-build update Nov 3rd

openpower/package/firestone-xml/firestone.mk, openpower/package/hostboot/hostboot.mk, openpower/package/palmetto-xml/palmetto-xml.mk
Updated versions: firestone.xml and hostboot
Tested on HW (IPL to petitboot)
=> op-build update Nov 12th

openpower/package/garrison-xml/garrison.mk
Pick up updates to FRU IDs to match Firestone and Membuf Sensor ID updates to allow thermal algorithm to work properly.
=> Modify XML Pointer

openpower/linux/linux-0001-xhci-Use-xhci_pci_remove-for-xhci-device-shutdown.patch, openpower/linux/linux-0002-Revert-usb-xhci-stop-everything-on-the-first-call-to.patch, openpower/linux/linux-0003-xhci-do-not-halt-the-secondary-HCD.patch, openpower/linux/linux-0004-powerpc-eeh-Fix-PE-location-code.patch, openpower/linux/linux-0005-Release-4.4.2-openpower1.patch
- Updated to 4.4.2 stable release
=> Release 4.4.2-openpower1 kernel

openpower/package/petitboot/petitboot.mk
This includes support for 'offb' framebuffers and IPMI network config overrides, and an update to the display format of platform versions.
=> Update Petitboot package

openpower/linux/linux-0001-xhci-Use-xhci_pci_remove-for-xhci-device-shutdown.patch, openpower/linux/linux-0002-Revert-usb-xhci-stop-everything-on-the-first-call-to.patch, openpower/linux/linux-0003-xhci-do-not-halt-the-secondary-HCD.patch, openpower/linux/linux-0004-drivers-drm-ast-Switch-SCU-to-VGA-output-on-POST.patch, openpower/linux/linux-0005-scsi-ignore-errors-from-scsi_dh_add_device.patch, openpower/linux/linux-0006-net-mlx4_core-Set-UAR-page-size-to-4KB-regardless-of.patch, openpower/linux/linux-0007-Release-4.4.4-openpower1.patch
Move to the latest stable release, and bring in a fakeroot fix from Stewart
=> Kernel 4.4.4 and Ubuntu 14.04 build fix

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/384)
=> Update readme to point to mailing list

openpower/configs/hostboot/barreleye.config
Signed-off-by: Johnny <johnny.cl.chang@foxconn.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/390)
=> Set PCA95X_8BIT support, turn on SBE update and IPL checkstop analysis.

openpower/package/VERSION.readme, openpower/package/openpower-pnor/openpower-pnor.mk, openpower/package/pkg-versions.mk
This adds versions for the kernel and petitboot packages, and explicitly points out the op-build and buildroot versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/382)
=> Add additional packges to the VERSION partition

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/413)
=> Bump petitboot to v1.0.0

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/448)
=> Bump petitboot to v1.0.1

openpower/package/occ/occ.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/459)
=> OCC Update 05/02/2016

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/495)
=> Bump Petitboot to v1.1.1

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/510)
=> petitboot: Bump version to 1.2.0

openpower/configs/openpower_p9_mambo_defconfig
The decision to use CCACHE or not should be up to the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/527)
=> Remove CCACHE from p9 defconfig

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/533)
=> petitboot: Bump version to v1.2.1

openpower/package/openpower-pnor/Config.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/529)
=> Changing skiboot pnor section to be compressed by default

openpower/scripts/release-notes
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/185)
=> Release notes tool.

openpower/package/petitboot/petitboot.mk, openpower/scripts/firenze-firmware-whitelist
https://github.com/open-power/op-build/issues/570
https://github.com/open-power/op-build/pull/573
https://github.com/open-power/op-build/pull/574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/575)
=> cherry pick radeon ucode and petitboot 1.2.2 update to op-build-1.10.y

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/592)
=> petitboot: Update to version v1.2.3

openpower/package/petitboot/petitboot.mk
(cherry picked from commit 181bc2ac963b381a87ae4c8cffb97f01c6aa332b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/595)
=> STABLE: petitboot: Update to version v1.2.3

openpower/package/occ/occ.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/614)
=> Add support for P9 occ compile

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/616)
=> petitboot: Update to v1.2.4

openpower/package/ppe42-binutils/Config.in, openpower/package/ppe42-gcc/Config.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/618)
=> Fix ppe42-binutils dependency

openpower/package/petitboot/petitboot.mk
Move to v1.3.0 and update some affected install rules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/628)
=> petitboot: Update to v1.3.0

openpower/package/hostboot/p9Patches/hostboot-0002-remove-attr-override-compile.patch, openpower/package/hostboot/p9Patches/hostboot-0004-remove-sbfw-check-hbDistribute.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/624)
=> Add patches for hostboot image distribution

openpower/configs/barreleye_defconfig, openpower/configs/firestone_defconfig, openpower/configs/garrison_defconfig, openpower/configs/habanero_defconfig, openpower/configs/palmetto_defconfig, openpower/package/hostboot-binaries/hostboot_binaries.mk, openpower/package/openpower-pnor/Config.in, openpower/package/openpower-pnor/openpower-pnor.mk
Note - this will fail and hashes will need to be updated once https://github.com/open-power/pnor/pull/50/ and https://github.com/open-power/hostboot-binaries/pull/9 are in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/635)
=> Add support for IMA (In Memory Accumulation) catalog pnor partiton

openpower/configs/witherspoon_defconfig
This will be replaced once SBE team has github support for building the SBE image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/652)
=> Add support for the standalone p9 SBE image

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/667)
=> petitboot: Update to v1.2.5

openpower/package/hostboot/p9Patches/hostboot-0004-target-pm-serverwiz1-and-2.patch, openpower/package/hostboot/p9Patches/hostboot-0005-add-nimbus-simics-xml.patch, openpower/package/witherspoon-xml/witherspoon.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/666)
=> Use nimbus targeting in Witherspoon until processMrw changes for serverwiz2 are in

ci/Dockerfile/fedora23, ci/build-all-defconfigs.sh, ci/build.sh
Ci improvements should have gone to master-next to begin with (my fault)
Additionally, extra merge commits in master vs master-next. This pull req solves that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/670)
=> master->master-next merge + Ci improvements back to master-next

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/689)
=> petitboot: Update to v1.3.1

openpower/configs/hostboot/witherspoon.config, openpower/package/hostboot/p9Patches/hostboot-0003-ast-2400-include-uartif.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/708)
=> Turn on console, AST_2500 for Witherspoon

openpower/scripts/firenze-firmware-whitelist
This is the one we need. Save a few hundred KB of space by not including
them all.
Signed-off-by: Joel Stanley joel@jms.id.au
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/711)
=> firmware-whitelist: Whitelist explict bnx2x firmware

openpower/package/ppe42-gcc/ppe42-gcc.mk
Point to the latest ppe42-gcc package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/714)
=> ppe42-gcc package update 10/31

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/761)
=> petitboot: Update to v1.3.2

openpower/package/hostboot/p9Patches/hostboot-0003-processMrw-fixes-to-work-with-latest-witherspoon.xml.patch, openpower/package/hostboot/p9Patches/hostboot-0005-filter_out_unwanted_attributes-initial-check-in.patch, openpower/package/hostboot/p9Patches/hostboot-0007-Add-filtering-script-to-openpower-distribution.patch, openpower/package/hostboot/p9Patches/hostboot-0008-Add-Hacked-values-for-VPD-attributes.patch, openpower/package/witherspoon-xml/witherspoon.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/770)
=> Fixes to get witherspoon xml working with latest hb

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/760)
=> petitboot: Update to v1.2.7

openpower/package/zaius-xml/zaius.mk
This needs to go in separately from https://github.com/open-power/op-build/pull/822
as the pnor change will fail to compile without https://github.com/open-power/op-build/pull/821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/823)
=> Update Zaius XML package version

openpower/package/hostboot-binaries/hostboot_binaries.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/827)
=> Update Hostboot binaires commit hash

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/844)
=> petitboot: Update to v1.4.1

openpower/package/witherspoon-xml/witherspoon.mk, openpower/package/zaius-xml/zaius.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/857)
=> Adding support for additional attribute files in P9

openpower/package/pkg-versions.mk
The VERSION partition is constructed in pkg-versions.mk, and has
the purpose of indicating to both the user and developer/support
what firmware build is on a particular machine.
This patch addresess a few issues with VERSION.
Firstly, the pkg-versions.mk code was making needlessly excessive calls
to git, which could be solved by using "git describe --always --dirty"
rather than going around and around.
Secondly, the information in VERSION was not always useful. Previously,
we'd get an entry like 'open-power-habanero-78d8928', which is only
useful if you posses a tree with that commit in it. With this patch,
instead you get 'open-power-habanero-v1.14-45-g78d89280c3f9' which tells
us a *lot* more information about what was used to build this image. The
same issue was with buildroot (was: …
=> VERSION: Improve logic behind and information in VERSION partition

openpower/package/garrison-xml/garrison.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/893)
=> Moving back garrison version to fix hardware bug

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/941)
=> petitboot: Update to v1.4.2

openpower/package/openpower-pnor/Config.in, openpower/package/openpower-pnor/openpower-pnor.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/946)
=> openpower-pnor: Build fixes

openpower/package/ima-catalog/ima-catalog.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/939)
=> Updated commit id

ci/Dockerfile/fedora25, ci/Dockerfile/ubuntu1404
Needed by kernel module signing.
Fixes: https://github.com/open-power/op-build/issues/960
Fixes: 034ff11c71f3ea49186781543dd3b6e88b191996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/977)
=> ci/Dockerfile: Add openssl devel dependencies

openpower/package/ppe42-binutils/ppe42-binutils.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/983)
=> Update ppe42-binutils version  ded0eff

CONTRIBUTING.md
In preparation for removing master-next.
If @e-liner is okay with it, I'll merge this branch and delete master-next by end of the week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/987)
=> CONTRIBUTING.md: Remove reference to master-next branch

openpower/package/romulus-xml/romulus.mk
Update the Romulus MRW version to the latest one with enabling async mode, fixing AVS bus and fixing PB/Nest bus freq
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1010)
=> Enable Romulus async mode with MRW updates

openpower/package/sbe/sbe-1000-Revert-Adu-moved-to-pibmem-for-lab-performance-im.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1023)
=> Patch for istep5 performance

openpower/package/hostboot/p9Patches/hostboot-0003-Apply-RINGOVD-to-SBE-image-prior-to-core-data.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1037)
=> OBUS related changes

openpower/package/ima-catalog/ima-catalog.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1030)
=> Fix imc-nest-offset and imc-nest-size fields and nx device node in POWER9 DTS file

openpower/package/sbe/sbe.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1048)
=> Latest SBE Image release

openpower/package/sbe/sbe.mk
Also, reindent to match other buildroot packages
This depends on https://github.com/open-power/sbe/pull/4 being accepted and the SBE_VERSION being updated accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1035)
=> sbe: Fix build commands

openpower/package/witherspoon-xml/witherspoon-xml-0002-set-ATTR_CLOCK_PLL_MUX-bit-14-0b1.patch, openpower/package/witherspoon-xml/witherspoon-xml-0003-Adjusting-A-Bus-Frequency.patch
- Using patches for now as there are commits in the witherspoon-xml
tree that fail to compile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1067)
=> op-build Witherspoon XML Update 05-08-2017

openpower/configs/hostboot/witherspoon.config
RTC:171824
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1088)
=> HTMGT-OCC: Enable HTMGT compile, Load/Start OCC

openpower/package/occ/occ.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1099)
=> Update OCC 5/22/17

openpower/package/hostboot/p9Patches/hostboot-0010-Updates-to-HBRT-runtime-interfaces.patch
- The skiboot package has a dependency on this change so
I will push this in as a patch as we resolve the
non-openpower dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1110)
=> Patch to update HBRT Runtime Interfaces

openpower/package/machine-xml/machine-xml.mk, openpower/scripts/release-notes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1107)
=> Update release notes tool

openpower/configs/firenze_defconfig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1136)
=> configs: Move firenze platform to Skiboot 5.4.5

openpower/configs/hostboot/zaius.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1156)
=> Enable OCC by default in Zaius

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1168)
=> petitboot: Bump to v1.4.3

openpower/package/hostboot/p8Patches/hostboot-0011-Convert-cmpi-to-cmpwi-to-fix-build-for-modern-binuti.patch, openpower/package/hostboot/p9Patches/hostboot-0004-Convert-cmpi-to-cmpwi-to-fix-build-for-modern-binuti.patch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1174)
=> hostboot: Add patches to fix cmpi assembly

openpower/package/hostboot/p8Patches/hostboot-0012-kernel-Update-assembly-for-modern-binutils.patch, openpower/package/hostboot/p9Patches/hostboot-0002-kernel-Update-assembly-for-modern-binutils.patch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1190)
=> hostboot: fix build with modern binutils

openpower/package/hostboot-binaries/hostboot_binaries.mk, openpower/package/hostboot/p9Patches/hostboot-0001-Increase-uart-delay.patch, openpower/package/hostboot/p9Patches/hostboot-1001-PM-HOMER-Header-Magic-word-change.patch, openpower/package/hostboot/p9Patches/hostboot-1002-PM-set-PGPE-and-SGPE-Timer-Select.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1203)
=> HCODE to hw062917b and patches for OCC on DD2.0

openpower/package/openpower-pnor/openpower-pnor.mk
- Point PNOR project to WOFDATA ECC UE fix
Signed-off-by: bofferdn@us.ibm.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1219)
=> Point PNOR project to WOFDATA ECC UE fix

openpower/package/sbe/sbe-0001-Restore-backward-compatibilty-of-SBE-image-with-HB-H.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1239)
=> Patch to resolve backward compatibility

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1242)
=> petitboot: Bump to v1.5.0

openpower/package/ima-catalog/ima-catalog.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1217)
=> ima-catalog: update version:  Added MBA nodes to P9 DTS files

openpower/scripts/release-notes
The witherspoon rename isn't as much fun as you'd think, and we have to jump through some hoops.
At the same time, this exposed a couple of bugs in the release-notes script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1247)
=> Release notes bugfixes

openpower/configs/hostboot/witherspoon.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1271)
=> Enable runtime checkstop analysis for witherspoon

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1277)
=> petitboot: Bump to v1.5.1

openpower/package/openpower-pnor/Config.in, openpower/package/openpower-pnor/openpower-pnor.mk
This commit adds in the base changes for a new PNOR section.
Currently, the hostboot changes are not complete for the support,
but this commit will enable the section to be filled with blank
data and will unblock testing.  Once hostboot changes are complete,
there will need to be a change in the pnor project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1312)
=> Base MEMD changes

openpower/configs/hostboot/zaius.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1358)
=> Enable Hostboot Runtime Checkstop Analysis on Zaius

openpower/configs/hostboot/p9dsu.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1388)
=> Enable FFDC Display in Hostboot For P9DSU

openpower/configs/hostboot/witherspoon.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1395)
=> Enable IPLtime Checkstop Analysis in Hostboot for Witherspoon

openpower/package/ima-catalog/ima-catalog.mk
- Modified compatible field for core and thread.
- Fixed POWER9 DTS files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1246)
=> ima-catalog: update version

openpower/package/openpower-pnor/openpower-pnor.mk
Signed-off-by: Charles P. Hofer <charles.hofer@ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1370)
=> Fixed PATH when building PNOR squashfs to use correct pflash binary

openpower/package/petitboot/petitboot.mk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1380)
=> petitboot: Bump to v1.6.0

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to version v1.4.4

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.6.1

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.6.2

openpower/package/ima-catalog/ima-catalog.mk
Segregate DD1 and DD2 core and thread level events.
Signed-off-by: Raj <drajarshi@in.ibm.com>
=> Modify core and thread level events for POWER9 DTS files

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.6.3

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.6.4

openpower/package/ima-catalog/ima-catalog.mk
Update scale information for XLink, MBA and PHB units.
Update event names for MCS, XLink and MBA units.
Add cb_offset to denote Control Block offset.
Signed-off-by: Raj <drajarshi@in.ibm.com>
=> Modify POWER9 DTS files

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.6.5

openpower/package/ima-catalog/ima-catalog.mk
Signed-off-by: Raj <drajarshi@in.ibm.com>
=> POWER9 DTS: Fix XLINK0 and XLINK1 event offsets

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.6.6

openpower/package/openpower-pnor/openpower-pnor.mk
Fixes: 735aec595bf418dc9050671be74db7bc08b66a39
Fixes: https://github.com/open-power/op-build/issues/1711
Fixes: https://github.com/open-power/pnor/commit/dccb9d427b9fb95b08af814218d06d9bee5392e6
=> PNOR fix for P8

openpower/package/hostboot-binaries/hostboot_binaries.mk
- There has been instability in HB + OPAL causing
boot hangs. Move back to working level until issues
can be resolved
=> Revert HCODE to hw012118a.911

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.7.0

openpower/scripts/release-notes
=> release-notes: Update env path

doc/release-notes/index.rst, doc/release-notes/v1.21.rst
=> doc: add v1.21 release notes

doc/release-notes/index.rst, doc/release-notes/v1.21.2.rst
=> doc: op-build v1.21.2 release notes

openpower/package/petitboot/petitboot.mk
=> petitboot: Bump to v1.7.1

README.md
=> README: point to docs, update platform list

openpower/package/ima-catalog/ima-catalog.mk
Modify unit names in the new Power9 IMA Catalog
=> Modify unit names in Power9 DTS files

openpower/configs/vesnin_defconfig, openpower/patches/vesnin-patches/hostboot/hostboot-0001-Increase-default-watchdog-timeout-to-300-seconds.patch, openpower/patches/vesnin-patches/hostboot/hostboot-0002-Fix-POS-and-SPD-VPD_REC_NUM.patch, openpower/patches/vesnin-patches/hostboot/hostboot-0003-Add-present-bits-info-based-on-pos.patch, openpower/patches/vesnin-patches/hostboot/hostboot-0004-Force-print-MCS-grouping-info-to-console.patch, openpower/patches/vesnin-patches/hostboot/hostboot-0005-Fill-empty-sensor-id-to-reserved-id-0xFF.patch, openpower/patches/vesnin-patches/hostboot/hostboot-0006-Delay-for-Centaure-1.2V-ready-on-128-DIMM-system.patch, openpower/patches/vesnin-patches/hostboot/hostboot-0007-Set-IBM-instead-of-AMI-for-eSEL.patch, openpower/patches/vesnin-patches/occ/occ-0001-Add-DIMM-temperature-sensors.patch
I can integrate these patches into OCC/Hostboot (P8 branch) with a configurable build via the c-preprocessor (defines), but I doubt that this work will be useful given that the P8 branches are almost not developing and these patches apply only to our hardware implementation.
=> Patch set for VESNIN server support

openpower/package/ima-catalog/ima-catalog.mk
Modify P9 DTS files to include Alink
=> Modify P9 IMA Catalog to include Alink

openpower/package/ima-catalog/ima-catalog.mk
Modify NX unit name in POWER9 DTS file
=> Modify NX unit name in POWER9 DTS file

openpower/package/ima-catalog/ima-catalog.mk
Add Centaur units for Power9 DTS files
=> Add Centaur units for P9 DTS files

ci/Dockerfile/ubuntu1604, ci/build-all-defconfigs.sh, ci/build-sdk.sh, ci/build.sh
- support building and caching of SDK
- use eatmydata
- build more than just legal-info, for the reasons.
=> CI: Speed up builds

doc/release-notes/v2.0.4.rst, doc/release-notes/v2.0.6.rst, doc/release-notes/v2.0.8.rst, doc/release-notes/v2.1-rc1.rst, doc/release-notes/v2.1.rst
=> doc: fix duplicate labels

openpower/package/ima-catalog/ima-catalog.mk
Add trace-node to Nimbus DD2 dts file
=> Add trace-node to Nimbus DD2 dts file

openpower/package/hostboot-p8/hostboot-p8.mk
Changes Included for package hostboot, branch master-p8:
30b88ed - Maxim Polyakov - 2018-10-01 - Support for extended FRU data for memory modules
=> op-build update 10-2-2018 for hostboot-p8

openpower/scripts/release-notes
Use real markdown-style line breaks and ignore the witherspoon_dev platform for platform-xml purposes.
=> release-notes script updates

openpower/package/openpower-pnor/openpower-pnor.mk, openpower/package/openpower-vpnor/openpower-vpnor.mk
Signed-off-by: Nick Bofferding <bofferdn@us.ibm.com>
=> Point PNOR package at commit which applies header to VERSION partition

openpower/package/petitboot/petitboot.mk
Includes a minor fix to the network requery feature
=> petitboot: Bump version to v1.7.3

openpower/package/libflash/Config.in, openpower/package/libflash/libflash.mk
=> opal-gard: add package as part of libflash build

openpower/package/petitboot/petitboot.mk
=> petitboot: Update to v1.7.4

doc/introduction.rst, doc/process/KernelTree.rst, doc/process/building-with-ci.rst, doc/process/index.rst, doc/release-notes/index.rst, doc/release-notes/v2.0.10.rst, doc/release-notes/v2.0.3.rst, doc/release-notes/v2.0.9.rst, doc/release-notes/v2.2-rc1.rst
A bunch of misc doc improvements that should be pretty uncontroversial.
@shenki I copied over the wiki page for KernelProcess and updated it a bit. What are your thoughts on maintaining that here rather than wiki? It does mean we can update it as we bump kernel version.
=> Random docs improvements

openpower/package/petitboot/petitboot.mk
Includes fix to avoid losing port information in PXE URLs.
=> petitboot: Bump to v1.7.5

openpower/package/sbe/sbe.mk
Pass SBE image name as input parameter to sbeOpDistribute.py
=> Update sbe.mk to pass SBE image name

doc/process/index.rst, doc/process/stable-rules.rst
=> doc: stable tree rules

openpower/package/openpower-pnor-util/openpower-pnor-util.mk
Oliver O'Halloran (2):
Use wc to calculate file sizes
Fix generate-tar on ppc64 hosts
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
=> openpower-pnor-util.mk: Bump to d23b5b74cf

openpower/package/ima-catalog/ima-catalog.mk
P9 DTS file for separate core/thread events and NVLINK fix
=> P9 DTS file for separate core/thread events and NVLINK fix

ci/build-all-defconfigs.sh, ci/build-sdk.sh, openpower/scripts/update-defconfigs.sh
The first PR in #3567 was too much, and there's actually a couple more things needing changes, so trying again in stages..
This obsoletes #3567
=> Scripts cleanup stage 1

openpower/package/ocmb-explorer-fw/Config.in
Signed-off-by: Bill Hoffa <wghoffa@us.ibm.com>
=> Update OCMB Explorer FW to v8.0 (CL407134)

.gitmodules, openpower/configs/blackbird_defconfig, openpower/configs/mihawk_defconfig, openpower/configs/mowgli_defconfig, openpower/configs/nicole_defconfig, openpower/configs/p9dsu_defconfig, openpower/configs/romulus_defconfig, openpower/configs/swift_defconfig, openpower/configs/witherspoon_defconfig, openpower/configs/zaius_defconfig
=> Bump buildroot to 2020.08.2

openpower/package/ocmb-explorer-fw/Config.in
Reverts open-power/op-build#3910
Latest level has seen issues.
=> Revert "Update OCMB Explorer FW to v8.0 (CL407134)"

openpower/package/ima-catalog/ima-catalog.mk
P10 IMA Catalog - PHB Prescaler update 
=> Updated IMA Catalog for P10

openpower/package/ima-catalog/ima-catalog.mk
=> Updated P10 IMA Catalog Nodes PB PEC MCS

openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
This commit will enable the exploitation of splitting the HBD PNOR
section into a RO and a RW section that will be dynamically detected
at Hostboot execution time.
=> Add Support for Hostboot HBD RO and RW sections

openpower/package/ocmb-explorer-fw/Config.in
Update to latest Explorer release
https://github.com/open-power/ocmb-explorer-fw/releases/tag/CL439412
Signed-off-by: Daniel Crowell <dcrowell@us.ibm.com>
=> Update Explorer OCMB Firmware to CL432412

openpower/configs/p10ebmc_defconfig
=> Move Rainier/Everest XML Pointers to GHE

openpower/package/hostboot-p10/hostboot-p10.mk
This commit changes the location where the IBM proprietary ECC
implementation files are expected to appear in the Hostboot project.
The files are still copied into the old location for
backwards-compatibility.
Signed-off-by: Zach Clark <zach@ibm.com>
=> Update the locations of the ECC implementation files for Hostboot

openpower/configs/p10ebmc_defconfig
=> Point everest-xml to Public GH

openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
81E00689	81E00689	AJSDA27A		sbeMeasurementStringFile lid for SBE trace parser script plugging into peltool.
81E0068A	81E0068A	AJSDA27B		sbeStringFile lid for SBE trace parser script plugging into peltool.
81E0068B	81E0068B	AJSDA27C		sbeVerificationStringFile lid for SBE trace parser script plugging into peltool.
Signed-off-by: Sunil Kumar <skumar8j@in.ibm.com>
=> Adding files sbe stringFile to the PNOR scratch dir for pel tool usage.

openpower/package/everest-xml/everest-xml.mk, openpower/package/rainier-2u-xml/rainier-2u-xml.mk, openpower/package/rainier-4u-xml/rainier-4u-xml.mk
Set a worse case scenario of creating a 4k blank WOF data file for when the WOF input is not supplied
Signed-off-by: chenduibm <duchen@us.ibm.com>
=> 4k blank WOF data file

openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
Signed-off-by: Sunil Kumar <skumar8j@in.ibm.com>
=> Moved the sbe String Files for peltool traces.

openpower/configs/p10ebmc_defconfig
=> Move rainier-xml Pointers to Public GH

openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
PFHB-5
Signed-off-by: Deb McLemore <debmc@us.ibm.com>
=> Hostboot Add Planar SPD PNOR support

openpower/package/bonnell-xml/bonnell-xml.mk
Update some variable names to more clearly identify the usage.
PFHB-5
=> Hostboot Build Planar SPD cleanup

openpower/package/hcode-p10/hcode-p10.mk, openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
Commit copies PM trexStringFiles from build directory to PNOR stage directory as LID.
=> p10_hcode: Partial support for parsing of traces in PM elog

openpower/package/pdata/Config.in
Joel Stanley (2):
configure: Run autoupdate
configure: Make aarch64 equivalent to arm
deepakala-k (1):
scripts: Use numerical sorting if applicable
=> phal: pdata: Bumped e28301d3..298b7970

openpower/package/sbe-odyssey/sbe-odyssey.mk
Change-Id: Ia9ebee4aba179fa3e8ad5ebeea11c2c549dd7ecd
=> Copy Odyssey debug tools

openpower/package/sbe-odyssey/Config.in
Change-Id: I05cacc39ccef534dc8e8ad0a2389a9962b6774ad
=> Updated sbe-ody commit to 29a66c63d0d9a2dda3e1974a4cff701ee24554d7

openpower/package/op-image-tools/Config.in
Change-Id: Ia8e11920c280c71756a02cbfa6dd8e9ac5cdf503
=> Updated op-image-tool commit to bcc5c038552362415121aa24c2a549d710861dc2

openpower/package/op-image-tools/Config.in
Change-Id: I2b4b6aa0e51a725481c8286777db99ffdc5661e1
=> Updated op-image-tool commit to 231dee804039d0fe363627f402065d5ba436f8dc

openpower/package/op-image-tools/Config.in
Change-Id: I3171596b100f2534c3c376b32c7523f4eeb33a1f
=> Update op-image-tool commit to 34c9cc99a90ac9700915077e925258d437f576ae

openpower/package/op-image-tools/Config.in
Change-Id: I43fd5cac75c05adfe076607c5c28fb11a97b735d
=> Update op-image-tools commit to de0a70d23c0ab87bc9a5032502874e012317fc4e
