open-power/op-build

- README
- openpower/package/p8-pore-binutils/p8-pore-binutils.mk
These two updates are for issues I found when building on Ubuntu 14.10. The update to p8-pore-binutils fixes building with gcc-4.9 host compilers.
The readme is updated with dependences that I found weren't installed on a Ubuntu 14.10 server install.
> Fixes for building on Ubuntu 14.10

- openpower/package/hostboot/hostboot-0011-eRepair-MBVPD-size-check-for-CDIMM-and-ISDIMM.patch
We found that current code causes dimm deconfigures on erepair errors instead of using a spare bus.  We verified this change fixes that.
> Add patch in to support erepair on OpenPower systems

- openpower/package/skiboot/skiboot.mk
This change brings us to 5.0-rc1, plus two openpower-specific fixes.
Alistair Popple (1):
memboot: Add a memboot flash backend
Ananth N Mavinakayanahalli (1):
fsp: Fix FSP irq initialization on PSIHBCR for resets
Anshuman Khandual (3):
FSP/LEDS: Modify handling of SPCN based LED commands
FSP/LEDS: Serialize the entire LED state change code and it's callback
FSP/LEDS: Roll back LED state update in case FSP command queuing fails
Benjamin Herrenschmidt (1):
Fixup "i" command in mambo scripts
Cyril Bur (2):
libflash: endian fixups for ecc.c
libflash: Improved ECC interface
Cédric Le Goater (15):
sparse: rtc_tod_state and rtc_tod_cache_dirty and be static
sparse: bt_backend can be static
flash: fix return value of flash_find_subpartition()
core: add a platform op to read sensors
dts: add …
> skiboot: Update to 9a3f68b

- openpower/package/habanero-xml/habanero-xml-0001-Revert-Merge-pull-request-18-from-open-power-bofferd.patch
- openpower/package/habanero-xml/habanero-xml-0002-Add-System-Fw-Fru-Id.patch
- openpower/package/habanero-xml/habanero-xml.mk
- openpower/package/hostboot/hostboot-0008-Update-SBE-Update-IPMI-Watchdog-call-to-use-HARD_RES.patch
- openpower/package/hostboot/hostboot-0009-Reject-IPMI-events-which-arent-destined-for-the-host.patch
- openpower/package/hostboot/hostboot-0010-Support-partial-good-Xbus.patch
- openpower/package/hostboot/hostboot-0011-Pull-model-name-and-serial-from-OSYS-record-if-avail.patch
- openpower/package/hostboot/hostboot-0012-Cap-off-the-TRACFBIN-such-that-nothing-exceeds-64-by.patch
- openpower/package/hostboot/hostboot-0013-Enable-vrml-mvpd.patch
- openpower/package/hostboot/hostboot-0014-Update-VPD-Fields-Use-for-Fru-Inventory.patch
- openpower/package/hostboot/hostboot-0015-Add-PNOR-Version-Information-to-IPMI-Fru-Inventory.patch
- openpower/package/palmetto-xml/palmetto-xml-0001-Revert-Merge-pull-request-12-from-open-power-bofferd.patch
- openpower/package/palmetto-xml/palmetto-xml-0002-Add-Sys-Fw-Fru-Id.patch
- openpower/package/palmetto-xml/palmetto-xml.mk
Hostboot Changes Included:
Iaa9c4e00325f8fa6efb7a9fca1275bcea2759308  -- Opal System info from OSYS
Id251307aa76259d8a290a92d9e9f3418b181bc3e -- SBE Update fix for new AMI level
I378e0763c5ca8c13830d0e6c057b24e6beb5dc8c -- Fix for AMI Sel causing power off in istep 6.5
If8f08d1602b4437aa0e72e6d2e8d99ca615a2c77 -- Limit Binary Trace cap at 64 bytes
Iaa4802e72e355acd03cb88e58c40d1069dd76ef5 -- FRU Inventory / VPD Mapping Update
Ib49fe67e9c6631b2b7ea0005e692c9aea6d84057 -- FRU Inventory PNOR Version Update
I245cd9947d5b7a05ff9a8f92ff18c658b1fe09d6 -- Support Partial Good Xbus
Habanero XML Changes:
Bring up to latest commit level: 4173b205b0a7dfd18a97f3a0d5319c9aad893035 with a patch to revert an XML change that didn't work with the given level of HB. Also included is an XML patch to include …
> Habanero Updates for SL

- openpower/package/VERSION.readme
- openpower/package/pkg-versions.mk
Originally openpower-pnor-version would only end up rebuilding
subpackages that don't have a version file, even if outdated.
> Add ability to force all subpackage version strings to be generated

- openpower/package/capp-ucode/capp-ucode.mk
Fixes issue for build systems where /bin/sh != /bin/bash
> Update capp-ucode to lastest repo

- openpower/package/skiboot/skiboot-0002-prd-Only-alter-host-presentation-bits-of-IPOLL-mask.patch
This commit picks up the following skiboot change for checkstop
analysis at runtime: http://patchwork.ozlabs.org/patch/464376/
> Pick up Skiboot Change for Checkstop Analysis At Runtime

- openpower/configs/firestone_defconfig
- openpower/configs/habanero_defconfig
- openpower/configs/palmetto_defconfig
- openpower/package/hostboot-binaries/hostboot_binaries.mk
- openpower/package/hostboot/hostboot.mk
- openpower/package/openpower-pnor/Config.in
- openpower/package/openpower-pnor/openpower-pnor.mk
This updates 3 packages.
Hostboot moves up to https://github.com/open-power/hostboot/commit/c646754e720b5cd21534425ca90bb414a4a3ff12
Hostboot-binaries moves up to https://github.com/open-power/hostboot-binaries/commit/22470e51b6342f9c307e28b3ea7cdb194ff954d4
Openpower-pnor moves up to https://github.com/open-power/pnor/commit/ed1682e10526ebd85825427fbf397361bb0e34aa
There are changes to all defconfig files to support the new parameter in update_image.pl and create_pnor_image.pl (addition of a variable defined winkle file name)
> Update hostboot, hostboot binaries and openpower-pnor packages

- openpower/package/occ/occ.mk
This OCC code drop has:
- Fixes for Issue#134
- Fix for incorrect socket power on call-home data
- Use correct slot for call-home log
- Support for 'Thermal Throttle' and 'Quick Power Drop' bits in the poll response
> OCC fixes for Tyan Issue 134 and other miscellaneous fixes

- openpower/package/pkg-versions.mk
Some SCM tags/versions can include the package name, in this event, we want
to exclude the package name from the generated version that ends up
in the VERSION partition.
This patch simply uses some sed to rip out 'package-' from anything from
git.
> Make pkg-versions.mk handle versions/tags with package name

- openpower/package/skiboot/skiboot.mk
Just one fix in 5.0.3 vs 5.0.2
core/mem_region: Create reservations of type REGION_HW_RESERVED
This fixes an issue where the PRD daemon cannot find reserved ranges
(eg, the homer image) that have been created by skiboot itself.
> Bump skiboot to skiboot-5.0.3

- README
Found by attempting op-build inside a debootstrapped vivid docker container on ppc64el.
> add missing build dependencies to Ubuntu instructions

- openpower/package/occ/occ.mk
Relevant changes on this OCC code drop:
- Fix for redundant master role
- Firestone fix for allowing full frequency range on slave OCCs
> Firestone OCC fixes for full frequency range on slave OCCs

- openpower/package/skiboot/skiboot.mk
Release notes are as follows:
Generic
-------
- cpu: fix hang in opal_reinit_cpus()
A bug introduced in 87690bd19dbb (skiboot-5.0) mean that if a host OS
was calling opal_reinit_cpus() with offline threads (e.g. kdump with
SMT!=8 on POWER8), we could, instead of kdumping, hang forever.
A side effect of this fix is that it is not possible to have a kdump
kernel be a different endian than the host kernel.
- Correctly set the Relative Priority Register
This means that on boot, the RPR will be set to a known value (the
same as phyp). This register controls the relative priority of each
thread in a core.
Previously, we were leaving it to whatever HostBoot set it to, which
may not be the desired value.
astbmc systems
--------------
- enable prd_init() for Firestone platform
- fix bug in hw/bt.c …
> Bump skiboot to skiboot-5.0.4

- openpower/package/hostboot/hostboot.mk
updated hostboot version to: 460fdf36b1fe3bc1157738cd1158a73893a1454b
Tested on habanero HW. Habanero booted without any non-recoverable errors.
> op-build hostboot package update June 26th

- openpower/package/skiboot/skiboot.mk
One commit from 5.0.4:
commit f5a7c43a163f5484d2bd2b8b74814abc23f1e92d
bt: Remove B_BUSY state
The bt layer used to cache the value of B_BUSY in the state machine,
assuming that once B_BUSY was cleared by the BMC that it would never
be set by the BMC again unless a message was sent to the bt interface.
This was mostly true for the AMI firmware except when the BMC reboots
which causes B_BUSY to be set. There may also be additional
circumstances which set B_BUSY. Therefore the bt layer must check
B_BUSY is clear before sending a message making the B_BUSY state
superfluous.
> Bump skiboot to skiboot-5.0.5

- openpower/package/skiboot/skiboot-0003-Makefile-specify-abiv1.patch
The current skiboot-0003-Makefile-specify-abiv1.patch does not apply,
due to changes in skiboot. Update the patch to suit.
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
> skiboot: Update Makefile patch to new skiboot version

- openpower/package/firestone-xml/firestone.mk
- openpower/package/habanero-xml/habanero-xml.mk
- openpower/package/hostboot/hostboot.mk
- openpower/package/palmetto-xml/palmetto-xml.mk
updated with hostboot, palmetto-xml, habanero-xml, and firestone-xml
latest versions.  Tested on habanero, palmetto, and firestone HW.
Note: Firestone tested with AMI level 0721n, there are known problems being
debugged with AMI level 0805a.
> op-build update August 7th

- openpower/package/skiboot/skiboot.mk
We'll do the final skiboot release before we tag the next op-build, but this should be really really quite close to what we include then. Pushing here for further testing.
> bump skiboot to 5.1.0-beta2

- openpower/package/skiboot/skiboot.mk
Over skiboot-5.1.0-beta2, we have the following changes:
- opal_prd now supports multiple socket systems
- fix compiler warnings in gard and libflash
Fixes https://github.com/open-power/op-build/issues/200
> Bump skiboot to 5.1.0

- openpower/package/skiboot/skiboot.mk
fixes build issues where HOSTCC is old (RHEL6)
fixes one CAPI bug (fault wasn't escalated to a fence)
https://github.com/open-power/op-build/issues/200 and https://github.com/open-power/op-build/issues/238
> skiboot-5.1.1

- openpower/package/occ/occ.mk
Changes to OCC build
- enable Call home in observation mode
- OCC Firmware support for Garrison
> OCC Firmware Update for Garrison

- openpower/package/openpower-pnor/openpower-pnor.mk
- openpower/package/skiboot/skiboot.mk
In future buildroot versions, the linux26 targets don't exist.
Currently, the buildroot we use for op-build supports both.
> Use linux-rebuild-with-initramfs rather than linux26

- openpower/package/occ/occ.mk
-PRDF: OCC write IPL or RUNTIME flag to PNOR
-Fix severity level of APSS_SLV_LONG_TIMEOUT TO Predictive
-Support FIR Collection on checkstop during IPL
> OCC firmware update to support ipl-time checkstop FIR collection

- openpower/package/skiboot/skiboot.mk
Over skiboot-5.1.2, we have the following changes:
- slot names for firestone platform
- fix display of LPC errors
- SBE based timer support
- on supported platforms limits reliance on Linux heartbeat
- fix use-after-free in fsp/ipmi
- fix hang on TOD/TB errors (time-of-day/timebase) on OpenPower systems
- On getting a Hypervizor Maintenance Interrupt to get the timebase
back into a running state, we would call prlog which would use
the LPC UART console driver on OpenPower systems, which depends on
a working timebase, leading to a hang.
We now don't depend on a working timebase in this recovery codepath.
- enable prd for garrison platform
- PCI: Clear error bits after changing MPS
Chaning MPS on PCI upstream bridge might cause error bits set on
downstream endpoints when system boots into …
> Bump skiboot to 5.1.3

- openpower/package/skiboot/skiboot.mk
fixes two pretty important issues
Over skiboot-5.1.3, we have the following changes:
- Rate limit OPAL_MSG_OCC to only one outstanding message to host
In the event of a lot of OCC events (or many CPU cores), we could
send many OCC messages to the host, which if it wasn't calling
opal_get_msg really often, would cause skiboot to malloc() additional
messages until we ran out of skiboot heap and things didn't end up
being much fun.
When running certain hardware exercisers, they seem to steal all time
from Linux being able to call opal_get_msg, causing these to queue up
and get "opalmsg: No available node in the free list, allocating" warnings
followed by tonnes of backtraces of failing memory allocations.
- Ensure reserved memory ranges are exposed correctly to host
(fix corrupted SLW image) …
> bump skiboot to 5.1.4

- openpower/package/petitboot/petitboot.mk
This request contains a fix for the petitboot makefile (installing to DESTDIR rather than the host filesystem), and updates us to d171258, where we've fixed a few issues found in test.
> Petitboot fixes

- openpower/package/occ/occ.mk
-Skip unnecessary firdata collection for EX targets
> OCC firmware update for Firestone

- openpower/package/occ/occ.mk
-Fix ipl time flag bit ordering for checkstop analysis
-DVFS bits in poll command will only be set if the frequency is below Turbo
> OCC Firmware update for IPL-time checkstop analysis

- openpower/custom/patches/dtc/dtc-0001-sort-unit-addresses-by-number.patch
- openpower/package/petitboot/petitboot.mk
Currently, dtc will output nodes unordered, which may cause issues when
assigning CPU numbers to NUMA nodes.
This change incorporates a pre-kexec hook to sort the device tree, and
a fix for dtc to order nodes by their unit number, to get a proper
sort ordering.
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
> dtc,petitboot: Sort device tree properties by unit number

- openpower/configs/hostboot/firestone.config
- openpower/configs/hostboot/garrison.config
- openpower/configs/hostboot/habanero.config
- openpower/configs/hostboot/palmetto.config
- openpower/package/occ/occ.mk
-Set config flag IPLTIME_CHECKSTOP_ANALYSIS
> Enable IPL-time Checkstop analysis for Palmetto, Habanero, and Firestone

- openpower/configs/hostboot/garrison.config
This commit turns on the SBE updates, and turns off the IPLTIME_CHECKSTOP_ANALYSIS config.
When the IPLTIME_CHECKSTOP_ANALYSIS config is on larger ddr4 garrison systems fail to IPL with an out of memory condition. Turning off this config is a workaround that will allow all machines to boot while this issue is root caused.
> Update Garrison Config 

- openpower/linux/linux-0001-xhci-Use-xhci_pci_remove-for-xhci-device-shutdown.patch
- openpower/linux/linux-0002-Revert-usb-xhci-stop-everything-on-the-first-call-to.patch
- openpower/linux/linux-0003-xhci-do-not-halt-the-secondary-HCD.patch
- openpower/linux/linux-0004-drivers-drm-ast-Switch-SCU-to-VGA-output-on-POST.patch
- openpower/linux/linux-0005-scsi-ignore-errors-from-scsi_dh_add_device.patch
- openpower/linux/linux-0006-net-mlx4_core-Set-UAR-page-size-to-4KB-regardless-of.patch
- openpower/linux/linux-0007-Release-4.4.6-openpower1.patch
This stable release has a fix to ensure the console messages will be
more reliably printed out when the host crashes or reboots.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/397)
> linux: Release v4.4.6-openpower1

- openpower/package/hostboot/hostboot-0002-GCC-4.9-Make-compiler-use-ELFv1-ABI.patch
At one point, Hostboot failed to run with -O3 when compiled with the
4.9.x series of compilers.  After internal investigation, we suspect
it was an issue with 4.9.0 specifically and 4.9.2+ appears to work
correctly.  We are using 4.9.3 here now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/407)
> Hostboot: Remove patch that restricted optimization.

- openpower/configs/hostboot/garrison.config
I have tested this on a large memory configuration machine in Rochester, and it appears we have gained back enough memory to boot up.
I wanted to test this with Jay's new memory tool, but it doesn't sound like that will capture memory consumption at every istep yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/410)
> Turn on IPLTIME_CHECKSTOP_ANALYSIS for Garrison

- openpower/package/openpower-pnor/openpower-pnor.mk
Without corresponding updates to makefiles (not yet approved for merge),
the newer openpower-pnor package breaks building a pnor with an error
from xz.
Fixes: 1d0a7b00d7578aafa8c8a0a81925e501453a01f1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/421)
> openpower-pnor: revert to working version

- openpower/package/petitboot/Config.in
Previously, we added dependency to petitboot.mk but we were missing
it from Config.in, which buildroot 2016.02 errors out on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/423)
> petitboot: depend on BR2_PACKAGE_LVM2 for devicemapper explicitly

- openpower/package/openpower-pnor/Config.in
- openpower/package/openpower-pnor/openpower-pnor.mk
We have already merged hostboot and open-power/pnor changes, this is the final change for RTC:125550.
This change will allow a user the option to XZ compress the skiboot image. The BR2_TARGET_SKIBOOT_XZ config will need to be enabled for the specific configuration, and then the skiboot image will be compressed. This change is only for compressing and decompressing the skiboot image section. If another section needs compression, we would have to enable decompression inside hostboot for that specific section, and make additional pnor changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/425)
> Adding XZ decompression functionality for skiboot

- openpower/package/occ/occ.mk
This includes removal of the IBM Confidential portions of SSX and its libraries, three defects, and an improvement to 'make clean' that was submitted via a pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/443)
> Update OCC FW 4/20/2016

- openpower/package/petitboot/petitboot.mk
With recent changes to Skiroot the petitboot-nc processes can start
before the pb-discover server. In this case /var/log/petitboot hasn't
been created by S15pb-discover yet, and each interface will fail to
fopen() its respective log file. This means each petitboot-nc process
will not produce logs the first time it is run.
Create the directory at build time to make sure we always get UI logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/442)
> petitboot: Create default log directory

- openpower/linux/linux-0001-xhci-Use-xhci_pci_remove-for-xhci-device-shutdown.patch
- openpower/linux/linux-0002-Revert-usb-xhci-stop-everything-on-the-first-call-to.patch
- openpower/linux/linux-0003-xhci-do-not-halt-the-secondary-HCD.patch
- openpower/linux/linux-0004-drivers-drm-ast-Switch-SCU-to-VGA-output-on-POST.patch
- openpower/linux/linux-0005-scsi-ignore-errors-from-scsi_dh_add_device.patch
- openpower/linux/linux-0006-net-mlx4_core-Set-UAR-page-size-to-4KB-regardless-of.patch
- openpower/linux/linux-0007-Release-4.4.8-openpower1.patch
- Linux 4.4.6 -> 4.4.8 stable release
- NVMe userspace tool now builds against libudev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/449)
> New kernel and nvme fixes

- openpower/package/openpower-pnor/openpower-pnor.mk
The xz decompression tool has been updated in a way
that no longer requires pnor changes.  This commit is removing
the extra op-build changes.  Note, there is also a pnor change
that needs to be merged with this commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/520)
> Removing extraneous xz op-build changes

- openpower/package/hostboot/hostboot.mk
hbDistrubte will determine if secureboot functionality was compiled
by looking in obj/genfiles/config.h. To simplify getting to that file
we can source env.bash once in the hostboot directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/528)
> Source env.bash when running hbDistribute

- openpower/package/Config.in
- openpower/package/barreleye-xml/Config.in
- openpower/package/barreleye-xml/barreleye-xml.mk
- openpower/package/common-p8-xml/Config.in
- openpower/package/firestone-xml/Config.in
- openpower/package/firestone-xml/firestone.mk
- openpower/package/garrison-xml/Config.in
- openpower/package/garrison-xml/garrison.mk
- openpower/package/habanero-xml/Config.in
- openpower/package/habanero-xml/habanero-xml.mk
- openpower/package/openpower-mrw/Config.in
- openpower/package/openpower-pnor/Config.in
- openpower/package/openpower-pnor/openpower-pnor.mk
- openpower/package/palmetto-xml/Config.in
- openpower/package/palmetto-xml/palmetto-xml.mk
- openpower/scripts/op-target-dependencies
Currently, there are a few issues with the dependency & configuration definitions for the PNOR and XML packages. This is preventing us from using some of the non-build targets, like `graph-depends` and `legal-info`, which don't currently work.
This proposed change populates the proper dependency info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/550)
> RFC: Fix dependencies for openpower-pnor & xml packages

- openpower/package/petitboot/petitboot.mk
- openpower/package/pkg-versions.mk
This allows us to get the full sha-dirty-patch version string in Petitboot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/532)
> Export PETITBOOT_VERSION to Petitboot autoreconf step

- openpower/package/capp-ucode/capp-ucode.mk
Based on (IBM internal bug tracker) SW322717
"SUE may be presented to OS in rare situations during a CAPI workload if EEH encountered"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/568)
> Update capp-ucode to latest master

- openpower/package/petitboot/petitboot.mk
Update to v1.2.2 and update the install rule for 80-set-stdout, which
has changed name since the last tagged version.
Fixes https://github.com/open-power/op-build/issues/570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/573)
> petitboot: Update to version v1.2.2

- openpower/scripts/firenze-firmware-whitelist
Some radeon chips require an additional _rlc.bin binary that doesn't
match the name of its other required binary files. Include the
BTC_rlc.bin binary as well for CAICOS chips.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/574)
> scripts: Include BTC binary for radeon cards

- openpower/package/capp-ucode/capp-ucode.mk
See https://github.com/open-power/op-build/pull/568
and some internal emails where I was suitably grumbley about timing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/576)
> cherry pick capp ucode for op-build 1.10.y

- openpower/package/petitboot/S14silence-console
Currently we set the current and default log levels to 0 (which is
invalid) and the minimum log level to 7 (which is very noisy). Update
the S14silence-console init script to set all these levels to the lowest
value of 1 instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/586)
> petitboot: Update setting of kernel log level

- openpower/package/petitboot/S14silence-console
Currently we set the current and default log levels to 0 (which is
invalid) and the minimum log level to 7 (which is very noisy). Update
the S14silence-console init script to set all these levels to the lowest
value of 1 instead.
(cherry picked from commit 2f6155e2ee8e555a2b70cbaf2de77233ff5f3293)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/588)
> STABLE: petitboot: Update setting of kernel log level

- openpower/package/openpower-pnor/openpower-pnor.mk
With this update: https://github.com/open-power/pnor/pull/49/files of op-build, we need some changes to match on the op-build side.  This is just removing the boolean from the makefile and leaving the xz_compression flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/590)
> Updating openpower-pnor to match xz changes from opPnor

- openpower/package/barreleye-xml/barreleye-xml.mk
- openpower/package/habanero-xml/habanero-xml.mk
Hostboot is introducing a new attribute file for attributes that are openpower only, and the FSP side is unaware of.  On the hostboot side, these files are only compiled with a configuration flag: CONFIG_OPENPOWER_ONLY.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/589)
> Adding in new attribute types files

- openpower/scripts/firenze-firmware-whitelist
The CAICOS series of radeon GPUs work on POWER but do not appear to
survive kexec. Remove support for them from Skiroot so that the GPU
won't be properly initialised until the host OS boots.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/637)
> scripts: Drop support for CAICOS cards

- openpower/scripts/firenze-firmware-whitelist
The CAICOS series of radeon GPUs work on POWER but do not appear to
survive kexec. Remove support for them from Skiroot so that the GPU
won't be properly initialised until the host OS boots.
(cherry picked from commit 379b91cc3974bfb414094e6e756d540e93ab1706)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/649)
> STABLE: scripts: Drop support for CAICOS cards

- ci/Dockerfile/fedora23
- ci/build-all-defconfigs.sh
- ci/build.sh
This patch adds support for running ci for individual platforms,
as well as it can generate firmware images for all the platforms.
For running ci to individual platforms:
DOCKER_PREFIX=sudo  ./ci/build.sh -p palmetto
DOCKER_PREFIX=sudo  ./ci/build.sh -p garrison
For running ci to all the platforms:
DOCKER_PREFIX=sudo  ./ci/build.sh -a
DOCKER_PREFIX=sudo  ./ci/build.sh
And also it contains missing packages required for fedora23 Dockerfile.
Signed-off-by: Pridhiviraj Paidipeddi <ppaidipe@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/580)
> Enhancements for op-build ci.

- openpower/package/hostboot-binaries/hostboot_binaries.mk
Pulls in P8 SBE change which lowers secure a-bus iovalids in secure mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/679)
> Update P8 SBE commit to point to b0831y_1638.860

- README.md
To a reader who has never used Buildroot before, it's not obvious that
op-build supports cross-compilation (indeed, cross-compiling from x86_64 to
ppc64 is the primary workflow of many developers). Document this
accordingly.
While we're here, make a few miscellaneous fixes:
* Improve formatting, get rid of some extraneous spaces etc
* Fix a couple of spelling and capitalisation errors
* Restructure some sentences to read more nicely
* For Ubuntu/Debian dependencies, note that the step on adding universe is
only relevant to Ubuntu
Reported-by: Bill Alexander <bill@ohwah.com>
Signed-off-by: Andrew Donnellan <andrew.donnellan@au1.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> README: add note on cross-compilation, miscellaneous improvements

- openpower/package/hostboot/p9Patches/hostboot-0006-fix-AST2500-config.patch
I missed a crucial letter in my patch. Without this change Witherspoon currently fails to build. This is being fixed in upstream Hostboot as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/734)
> Fix SFT_IS_AST2500 config patch in src/usr/pnor/HBconfig

- openpower/scripts/firmware-whitelist
The whitelist was matching bnx2* as ok, so everything in bnx2x was being
left in the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/740)
> firmware-whitelist: Make whitelist accurate

- openpower/package/hostboot/p9Patches/hostboot-0003-fix-makefile-comment.patch
by bringing in patch currently in review that fixes makefile comments
to be actual comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/745)
> Fix Witherspoon build

- openpower/package/ppe42-gcc/ppe42-gcc.mk
This latest fixes a buffer overflow in the compiler observed when building
under Ubuntu 14.04.
Signed-off-by: Robert Lippert <rlippert@google.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/779)
> package/ppe42-gcc: update to latest version 10-29-2016

- openpower/overlay/etc/init.d/S10udev
- openpower/overlay/etc/init.d/S17udevsettle
Add S10udev and S17udevsettle to the overlay to replace the existing
S10udev from buildroot. `udevadm settle` can wait up to 30 seconds which
delays the start of pb-discover and can cause important information to
miss the Petitboot UI. Start pb-discover first and then settle to have
the UI receive all events and bring up devices in the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/789)
> overlay: Move `udevadm settle` to after pb-discover start

- op-build-env
If you don't have the buildroot submodule present, the build fails in a
confusing way:
op-build witherspoon_defconfig
make: Entering directory '/home/benh/op-build/buildroot'
make: *** No rule to make target 'witherspoon_defconfig'.  Stop.
make: Leaving directory '/home/benh/op-build/buildroot
This change gives the user a better chance:
$ . op-build-env
Please make sure you've checked out the buildroot submodule
git submodule init && git submodule update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/865)
> op-build-env: warn when user forgets buildroot submodule

- ci/Dockerfile/fedora23
CI scripts failed to build PNOR image for habanero platform
on fedora os.
This patch fixes this issue by adding the required perl module
into corresponding docker file (perl(ExtUtils::MakeMaker))
Signed-off-by: Pridhiviraj Paidipeddi <ppaidipe@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/860)
> Add missing perl module to fedora Docker file.

- README.md
Fedora 23 is out of support, mention current Fedora.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/874)
> README: Mention current Fedora

- openpower/configs/romulus_defconfig
- openpower/package/romulus-xml/romulus.mk
1. Update the xml to latest version
2. Sync up the change for kernel header
3. Sync up the change to fix the HDAT_I2C_DEV_PURPOSE miss define problem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/905)
> Update romulus MRW config

- openpower/package/ppe42-gcc/ppe42-gcc.mk
If host-ppe42-gcc is built against a buildroot version of 2016.11
then the dependency of ppe42-binutils is ignored as it is not
specified as a host dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/864)
> ppe42-gcc: Host package should depend on host-ppe42-binutils

- openpower/package/occ/occ.mk
Our Jenkins testing structure has had a lot of changes recently and as such, we got a false positive on a pull request this morning.  This is reverting those changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/962)
> Reverting occ changes that were incorrectly merged

- README.md
Running op-build on Ubuntu 16.04 without having libssl-dev installed leads to the following error:
`scripts/sign-file.c:25:30: fatal error: openssl/opensslv.h: No such file or directory`
More verbose information:
```
[...]
tk@tpt:~/git/op-build$ time op-build
make: Entering directory '/home/tk/git/op-build/buildroot'
[...]
scripts/sign-file.c:25:30: fatal error: openssl/opensslv.h: No such file or directory
compilation terminated.
scripts/Makefile.host:107: recipe for target 'scripts/sign-file' failed
make[3]: *** [scripts/sign-file] Error 1
make[3]: *** Waiting for unfinished jobs....
HOSTCC  scripts/dtc/srcpos.o
HOSTCC  scripts/dtc/checks.o
HOSTCC  scripts/mod/modpost.o
HOSTCC  scripts/mod/file2alias.o
HOSTCC  scripts/dtc/util.o
SHIPPED scripts/dtc/dtc-lexer.lex.c
SHIPPED …
```
> add libssl-dev to requirements for Ubuntu/Debian

- openpower/package/petitboot/petitboot.mk
30-dtb-updates is only created when dtc is selected.
Signed-off-by: Arthur Heymans <arthur@aheymans.xyz>
Naming and hook update fixed by:
This fixes and supersedes https://github.com/open-power/op-build/pull/697
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1032)
> Make installing 30-dtb-updates depend on BR2_PACKAGE_DTC

- openpower/package/ppe42-gcc/ppe42-gcc.mk
This fixes issues building the host-ppe42-gcc with a cleanly checked out
op-build.
Signed-off-by: William A. Kennington III <wak@google.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1024)
> ppe42-gcc: Fix implicit dependencies

- openpower/package/capp-ucode/capp-ucode.mk
p9 capp ucode is added to the same partition for now, as we still have space (there's even space for one more)
Signed-off-by: Frederic Barrat <fbarrat@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1042)
> Add capp ucode for p9

- openpower/package/witherspoon-xml/witherspoon-xml-0001-Fix-FABRIC-GROUP-CHIP-settings-on-2nd-socket.patch
- openpower/package/witherspoon-xml/witherspoon.mk
- Use the PBAX fixes + a patch to make the PBAX fixes work
- There are some OBUS XML changes intertwined that cause
IPL failures. HB changes are in flight, so for now
just pick up the working XML changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1061)
> Witherspoon XML Package Update 05/03/17

- openpower/configs/hostboot/witherspoon.config
- openpower/configs/hostboot/zaius.config
- This will enable Hostboot to use the BMC Mbox protocol to use
the BMC to do PNOR accesses
- Enable for Witherspoon + Zaius systems
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1119)
> Enable BMC Mbox Protocol

- openpower/package/petitboot/66-add-sg-module.rules
- openpower/package/petitboot/petitboot.mk
On open power system update_flash -d option failed to display FW details
which is due to on petitboot sg kernel module was not loaded.
This patch is to introduce udev rule to load "sg" kernel module
automatically when petitboot is up.
Signed-off-by: Mamatha Inamdar <mamatha4@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1117)
>     Load 'sg' kernel module automatically in petitboot

- openpower/package/openpower-pnor/Config.in
All P9 machines need to have a default for these variables, otherwise they fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1141)
> Updating wofdata variables to have defaults for all p9 machines

- openpower/overlay/etc/init.d/S18lvm
- openpower/overlay/lib/udev/rules.d/10-dm.rules
- openpower/overlay/lib/udev/rules.d/11-dm-lvm.rules
- openpower/overlay/lib/udev/rules.d/13-dm-disk.rules
- openpower/overlay/lib/udev/rules.d/95-dm-notify.rules
Adds the necessary udev rules and an initscript to scan for and activate LVM logical volumes.
Note that Petitboot will only recognise logical volumes after a related change in Petitboot (see http://patchwork.ozlabs.org/patch/776113/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1153)
> Add LVM support

- openpower/package/hostboot-binaries/hostboot_binaries.mk
- openpower/package/occ/occ.mk
Grab latest HCODE image in preparation for P9 DD2.0
Has a co-req to OCC 53c19c213e9ca6769bca90e864291898c5783a47,
but that has compile issue, so tieing to fixed commit of
1dc97a688e32e63420533bfde8c6d7d2996619ea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1161)
> Update HCODE to hw061517a.910

- openpower/package/machine-xml/machine-xml.mk
This will allow the generation of PersistRwAttrList.csv in
output/staging/openpower_mrw_scratch/ instead of buildroot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1196)
> xmltohb.pl: pass mrw scratch dir as src-output-dir

- openpower/scripts/release-notes
The redbud platform uses the witherspoon-xml repository. There is no
redbud-xml repository so ignore it when creating a list of -xml
repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1237)
> scripts/release-notes: Don't try to clone redbud-xml

- openpower/package/p8-pore-binutils/p8-pore-binutils.mk
Otherwise, with GCC7 (default on Fedora 26) we fail to build with errors
like this:
coffgen.c:1996:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
Fixes: https://github.com/open-power/op-build/issues/1249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1250)
> p8-pore-binutils: build with -Wno-error

- openpower/package/libflash/Config.in
- openpower/package/libflash/libflash.mk
- openpower/package/petitboot/Config.in
Extend the libflash package to also install the pflash utility. This
enables users to query and modify the PNOR safely from the host, as well
as supporting future automation changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1166)
> Update libflash and install pflash utility

- openpower/scripts/release-notes
The proliferation of witherspoon flavours has confused the release-notes
script again, causing it to attempt to clone the nonexistent
witherspoon-{redbud,sequoia}-xml repo.
Handle these extra variants to make sure we only clone the actual
witherspoon-xml repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1299)
> release-notes: Don't try to clone witherspoon-foo-xml

- openpower/scripts/release-notes
The release-notes script currently specifies HTTP URLs for each project
repository. These are all Github URLs and recently there's been a 50/50
chance of Github either a) redirecting to HTTPS or b) timing out.
Update all URLs to use HTTPS so that the release-notes script can
actually clone them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1347)
> release-notes: Clone project repos via HTTPS

- openpower/configs/hostboot/witherspoon.config
Change Hostboot behavior to do a regular terminate in manufacturing
mode instead of doing infinite loop since we have a BMC codestack
that supports not rebooting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1424)
> Switch to term-on-error for mfg mode errors

- openpower/package/libflash/libflash.mk
The recent change to install host-pflash can cause the build to fail
since PFLASH_VERSION is not set:
version.c:1:2: error: #error You need to set PFLASH_VERSION environment variable
#error You need to set PFLASH_VERSION environment variable
^
rules.mk:39: recipe for target 'version.o' failed
PFLASH_VERSION is set from SKIBOOT_VERSION, add it to the build command
as we do for normal libflash build command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1385)
> libflash: Set SKIBOOT_VERSION for host-libflash

- openpower/configs/barreleye_defconfig
- openpower/configs/firenze_defconfig
- openpower/configs/firestone_defconfig
- openpower/configs/garrison_defconfig
- openpower/configs/habanero_defconfig
- openpower/configs/p9dsu_defconfig
- openpower/configs/pseries_defconfig
- openpower/configs/romulus_defconfig
- openpower/configs/witherspoon-redbud_defconfig
- openpower/configs/witherspoon-sequoia_defconfig
- openpower/configs/zaius_defconfig
- openpower/configs/zz_defconfig
The 2017.08 Buildroot update introduced a new option
"BR2_SYSTEM_ENABLE_NLS" which is by default set to false.
Set this to true in all platforms that use translations to re-enable
them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1438)
> configs: Re-enable translations

- openpower/package/capp-ucode/capp-ucode.mk
Point the capp-ucode.mk to latest capp-ucode tagged release for POWER9
DD-2.0 chip.
Signed-off-by: Vaibhav Jain <vaibhav@linux.vnet.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1421)
> Add capp ucode for P9-DD2.0

- openpower/package/hostboot-binaries/hostboot_binaries.mk
- openpower/package/hostboot/p9Patches/hostboot-0001-Remove-support-for-P9N-Nimbus-DD1.0.patch
- Due to space contraints, critical workarounds for DD1.0
have been dropped. DO NOT USE ON DD1.x systems. An HB
patch is included to detect a Nimbus DD1.0 System and
halt the IPL with an error message to the console.
Changes included for hostboot-binaries:
- Move HCODE to hw091517b.910
Changes included for hostboot (as a patch):
3fc1354 - Dean Sanner - 2017-09-19 - Remove support for P9N (Nimbus) DD1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1459)
> op-build Remove DD1.0 Support / Add DD2.x fixes 09-19-2017

- openpower/scripts/release-notes
The release-notes script gets confused by the existence of both
witherspoon_sequoia_defconfig and witherspoon_defconfig. In this
scenario witherspoon_sequoia_defconfig only exists to placate the CI
process, so treat it as if it does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1468)
> release-notes: Update to account for single witherspoon platform

- openpower/package/openpower-pnor/openpower-pnor.mk
op-build will now make a tar archive of the files useful for debugging.
The full list of files:
-hbicore.bin.modinfo
-hbicore.list.bz2
-hbicore.syms
-hbirt.bin.modinfo
-hbirt.list.bz2
-hbirt.syms
-hbotStringFile
-ecmd-debug-framework.pl
-skiboot.elf
-skiboot.map
-.config
-vmlinux
-System.map
-zImage.epapr
RTC:126574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-power/op-build/1446)
> Save Debug Data During op-build

- openpower/package/petitboot/petitboot-console-ui.rules
Switching from vt100 to the linux termtype appears to solve the problem
of incorrectly displaying ncurses extended characters used for parts of
the window border. This error can occur, for example, by opening a SOL
session when the Petitboot UI is already drawn:
```
Petitboot (v1.5.0-p60e3423)                          8335-GCA 2108ECA
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
System information
System configuration
System status log
Language
Rescan devices
Retrieve config from URL
*Exit to shell
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
Enter=accept, e=edit, n=new, x=exit, l=language, g=log, h=help
```
Switching to 'linux' correctly draws the line borders even when starting
a session late.
Signed-off-by: Samuel …
> petitboot: Use linux terminal type

- openpower/package/ima-catalog/ima-catalog.mk
- Unit nodes for NVLink added for consistency
Signed-off-by: Raj <drajarshi@in.ibm.com>
> Add unit nodes for nvlink in P9 DTS files

- openpower/package/libflash/libflash.mk
Update libflash to the latest upstream commit, in particular to pick up
the commit "pflash: Fix erase command for unaligned start address",
which fixes an issue resulting in incomplete erases.
> libflash: Update to upstream version v5.8-123-gc06ed583

- openpower/configs/hostboot/p9dsu.config
- openpower/configs/hostboot/romulus.config
- openpower/configs/hostboot/witherspoon.config
- openpower/configs/hostboot/zaius.config
Removed the HOST_HCDB_SUPPORT directive from the config file. It
will now be controlled from the hwas/HBconfig file.
> Removed the HOST_HCDB_SUPPORT directive

- openpower/package/capp-ucode/capp-ucode.mk
Point the capp-ucode.mk to latest capp-ucode tagged release for POWER9
DD-2.1 chip.
Signed-off-by: Vaibhav Jain <vaibhav@linux.vnet.ibm.com>
> Add capp ucode for P9-DD2.1

- openpower/package/ppe42-gcc/ppe42-gcc.mk
Supersedes  https://github.com/open-power/op-build/pull/1566
Doug Gilbert (4):
Prevent unsupported load/store index updateinstructions on PPE
Indicate that PPE42 fused branch instructions modify the CR
unsupported insn for bswap emitted
Merge pull request #5 from dgilbert999/gcc-4_9_2-ppe42
Douglas Gilbert (1):
Fix compile issue when compiling with gcc 6
Patrick Williams (2):
Merge pull request #3 from dgilbert999/gcc-4_9_2-ppe42
Merge pull request #4 from dgilbert999/gcc-4_9_2-ppe42
Suggested-by: Douglas Gilbert <dgilbert999@netscape.net>
> Bump ppe42-gcc to c13849780c80d1ed466efbeaabcc663fe48cd87d

- openpower/package/openpower-ffs/openpower-ffs.mk
Christian Geddes (1):
Update libffs to increment part entry and TOC size info
Stewart Smith (40):
add .travis.yml for travis-ci
add running of fpart test to travis
Remove unused memory_leak_detection.h
remove unused table and table_iter
remove unused bitset
remove unused map and map_iter
remove unused timer.h
remove unused vector and vector_iter
remove unused stack.h
remove unused dispatch and watch
remove unused array
remove unused heap
remove unused signal
remove unused db.c/db.h
remove unused slab
remove more unused memory_leak_detection code
remove crc32 - use sha1sum in test case instead
remove likely/unlikely: nothing is *that* perf critical
Remove #define parity __builtin_parity
remove unused ctz builtin defines
Move to autotools
remove custom assert implementation and exception.c …
> Bump openpower-ffs to e99543bb1729c76044f6fdd0d24a2fec5d543177

- openpower/package/capp-ucode/capp-ucode.mk
Point the capp-ucode.mk to latest capp-ucode tagged release for POWER9
DD-2.2 chip.
Signed-off-by: Vaibhav Jain <vaibhav@linux.vnet.ibm.com>
> Add capp ucode for P9-DD2.2

- openpower/configs/linux/skiroot_p9_defconfig
i.e. let's die in a horrific fire if stop states aren't working
correctly.
> skiroot_p9_defconfig: Enable powersave in Petitboot kernel

- openpower/configs/linux/skiroot_defconfig
- openpower/configs/linux/skiroot_p9_defconfig
This makes booting an OS on a machine with an IPR adapter a
lot quicker, avoiding a lot of reset time.
Suggested-by: Brian King <brking@linux.vnet.ibm.com>
> linux/defconfig: Set ipr.fast_reboot=1

- openpower/configs/barreleye_defconfig
- openpower/configs/firenze_defconfig
- openpower/configs/firestone_defconfig
- openpower/configs/garrison_defconfig
- openpower/configs/habanero_defconfig
- openpower/configs/openpower_mambo_defconfig
- openpower/configs/openpower_p9_mambo_defconfig
- openpower/configs/p9dsu_defconfig
- openpower/configs/palmetto_defconfig
- openpower/configs/pseries_defconfig
- openpower/configs/romulus_defconfig
- openpower/configs/witherspoon_defconfig
- openpower/configs/zaius_defconfig
- openpower/configs/zz_defconfig
GCC builds this library in order to enable the -fsanitize error detection
features. This part of the compile takes several minutes on a Westmere
Xeon build server, and to make it worse the build serialises at that
point.
Our GCC is 6.4 at this point. Running 'op-build toolchain' shows a
saving of about 33% (4 minutes) on a 40 core machine and a 25% (6
minutes) on a 2 core machine.
We build neither the kernel nor userspace with any of these tools, and
probably never will in production.
In order to save build time disable libsantizer for GCC builds.
> gcc: disable libsanitizer

- openpower/package/libflash/libflash.mk
Not all of these are applicable to libflash/pflash as we use them,
but this gets us onto the latest release.
Cyril Bur (11):
libflash/mbox-flash: Always close windows before opening a new window
libflash/mbox-flash: Move sequence handling to driver level
libflash/mbox-flash: Allow mbox-flash to tell the driver msg timeouts
libflash/mbox-flash: Simplify message sending
libflash/mbox-flash: Use BMC suggested timeout value
libflash/mbox-flash: Use static arrays of function pointers
libflash/mbox-flash: Understand v3
libflash/mbox-flash: Add the ability to lock flash
libflash/test: Add tests for mbox-flash
pflash: Respect write(2) return values
libflash/blocklevel: Correct miscalculation in blocklevel_smart_erase()
Frédéric Bonnard (1):
Add man pages for xscom-utils and pflash
Stewart Smith …
> Bump libflash to v5.10.1

- .gitmodules
- openpower/configs/barreleye_defconfig
- openpower/configs/firenze_defconfig
- openpower/configs/firestone_defconfig
- openpower/configs/garrison_defconfig
- openpower/configs/habanero_defconfig
- openpower/configs/openpower_mambo_defconfig
- openpower/configs/openpower_p9_mambo_defconfig
- openpower/configs/p9dsu_defconfig
- openpower/configs/palmetto_defconfig
- openpower/configs/pseries_defconfig
- openpower/configs/romulus_defconfig
- openpower/configs/vesnin_defconfig
- openpower/configs/witherspoon_defconfig
- openpower/configs/witherspoon_dev_defconfig
- openpower/configs/zaius_defconfig
- openpower/configs/zz_defconfig
https://git.buildroot.net/buildroot/plain/CHANGES?id=2018.05
http://lists.busybox.net/pipermail/buildroot/2018-June/222697.html
Highlights for OpenPower Firmware:
- Buildroot GCC default moves to 7: We're stuck on GCC 6 due to Hostboot :(
- Git caching: you don't need to re-clone from scratch when moving to a
different version of a package
Updated packages:
busybox: 1.27.2 -> 1.28.4
glibc: glibc-2.26-146 -> glibc-2.27-57
dropbear: 2017.75 -> 2018.76
ethtool: 4.13 -> 4.16
ncurses: 6.0 -> 6.1
util-linux: 2.31.1 -> 2.32
Updated host packages:
lz4: v1.7.5 -> v1.8.2
ncurses: 6.0 -> 6.1
gcc-initial: 6.4.0 -> 7.3.0
gcc-final: 6.4.0 -> 7.3.0
lzip: 1.19 -> 1.20
gawk: 4.1.4 -> 4.2.1
libopenssl: 1.0.2n -> 1.0.2o
squashfs: 3de1687d7432ea9b302c2db9521996f506c140a3 -> …
> buildroot: Move to 2018.05 release

- openpower/package/openpower-pnor/openpower-pnor.mk
So that when you untar them you don't end up with a heap of files in
your current working directory.
> openpower-pnor: Add path nside debug object tarball

- openpower/overlay/bin/msglog
This adds a one line shell script that can be used to display the OPAL
msglog without having to type out the full path.
> openpower: Add msglog tool to skiroot

- ci/build.sh
Also fixes the failure message.
> ci: Use uname rather than arch

- openpower/custom/patches/busybox/busybox-0001-udhcp-add-option-211-reboot-time.patch
- openpower/package/petitboot/petitboot.mk
Petitboot v1.7.2 includes several logging improvements and a backport of the network re-query feature. The busybox patch provides the reboottime option required by re-query.
> Update to Petitboot v1.7.2 and include udhcpc dependency

- ci/build-all-defconfigs.sh
- ci/build.sh
Some small enhancements to the CI build scripts, mainly motivated by trying to set up a Jenkins-in-docker server behind a proxy:
- Use `--network=host`
- Allow a custom mount point (so we can..)
- Specify custom locations for the download and ccache directories.
> Improvements to the CI build scripts

- ci/build-all-defconfigs.sh
- ci/build.sh
Tweak where `build-all-defconfigs.sh` cleans up its output directory to make post-build processing and/or debugging easier, and add an option to generate the `legal-info` target during the build.
> Updates to CI scripts

- openpower/package/openpower-pnor/openpower-pnor.mk
- The HB tools were losing their file structure,
which caused commands like ecmd-debug-framework
to fail as the required perl modules were not
in the expected location
> Enable host_fw_debug.tar file to keep file structure

- ci/Dockerfile/ubuntu1604
The docker image of Ubuntu 16.04 doesn't have 'colrm' utility which is
used in Perl script 'addimgid' (hostboot build tools) to construct an ID string
of hostboot image:
https://github.com/open-power/hostboot/blob/master/src/build/tools/addimgid#L39
As result, variable hbi_ImageId in hostboot is allways empty.
Installing bsdmainutils package resolves this problem.
Signed-off-by: Artem Senichev <a.senichev@yadro.com>
> Add bsdmainutils to Ubuntu docker

- doc/requirements.txt
The latest release (1.8) contains a bug when building the latex output.
Pin the version to 1.7.9 while we wait for a fix.
Upstream bug: https://github.com/sphinx-doc/sphinx/issues/5419
> docs: Force sphinx to be version 1.7.9

- .gitmodules
- openpower/configs/barreleye_defconfig
- openpower/configs/firestone_defconfig
- openpower/configs/garrison_defconfig
- openpower/configs/habanero_defconfig
- openpower/configs/p9dsu_defconfig
- openpower/configs/palmetto_defconfig
- openpower/configs/pseries_defconfig
- openpower/configs/romulus_defconfig
- openpower/configs/vesnin_defconfig
- openpower/configs/witherspoon_defconfig
- openpower/configs/witherspoon_dev_defconfig
- openpower/configs/zaius_defconfig
Set BR2_GCC_VERSION_6_X=y in all of the configs that include hostboot,
as the default has moved to GCC 7 and hostboot cannot build with a
modern compiler.
Host packages updated:
libxml2: 2.9.7 -> 2.9.8
lz4: v1.8.1.2 -> v1.8.2
zstd: v1.3.3 -> v1.3.5
dtc: 1.4.4 -> 1.4.7
Shipped packages updated:
busybox: 1.29.0 -> 1.29.2
linux-firmware: 65b1c68c63f974d72610db38dfae49861117cae2 -> 8d69bab7a3da1913113ea98cefb73d5fa6988286
ethtool: 4.15 -> 4.16
util-linux: 2.32 -> 2.32.1
dtc: 1.4.4 -> 1.4.7
elfutils: 0.169 -> 0.171
> buildroot: Move to 2018.08

- openpower/package/hostboot-p8/hostboot-p8.mk
- openpower/package/openpower-pnor/openpower-pnor.mk
This commit adds support for an attribute/targeting Read-Write partition
called HBD_RW ("HB_DATA_RW") in P8 OpenPower systems. The P8 PNOR XML
Layout files had this partiontion added, while the P9 PNOR XML Layout files
did not.  The common PNOR files update_image.pl and create_pnor_image.pl
were udpated to handle whether or not HBD_RW was part of the layout.
The hostboot-p8 code (via the hostboot 'master-p8' branch) was also updated
to handle this new HBD_RW PNOR partition.
Signed-off-by: Mike Baiocchi <mbaiocch@us.ibm.com>
> Add Supprt for P9 Attribute/Targeting Read/Write Partition

- openpower/package/openpower-pnor/openpower-pnor.mk
This commit pulls in an update to the P8 PNOR XML Layout files
that were causing build problems for the VESNIN configuration.  The
change is that the combined size of the HBD and HBD_RW partitions
was redistributed to HBD and HBD_RW to allow for the fact that for
P8 systems there was much more read-only attribute/targeting content
then read-write content.
Signed-off-by: Mike Baiocchi <mbaiocch@us.ibm.com>
> Pull in P8 PNOR XML Layout Fix for HBD/HBD_RW Partitions

- openpower/package/libflash/libflash.mk
Previously we were based off skiboot v5.10.1, let's bump things
up to where we're going to do the next skiboot release from.
Rough changelog (for libflash/ and external/pflash/ in skiboot):
Adriana Kobylak (1):
pflash: Add --skip option for reading
Andrew Jeffery (11):
libflash: Add ipmi-hiomap
astbmc: Prefer ipmi-hiomap for PNOR access
platform: Restructure bmc_platform type
libflash/ipmi-hiomap: Cleanup allocation on init failure
libflash/ipmi-hiomap: Improve event handling
libflash/ipmi-hiomap: Restore window state on window/protocol reset
libflash/ipmi-hiomap: Use error codes rather than abort()
libflash/test: Rewrite Makefile.check to improve scalability
libflash/ipmi-hiomap: Fix argument type warning on x86-64
libflash/ipmi-hiomap: Add support for unit tests
libflash/ipmi-hiomap: …
> pflash and libflash: bump to v6.2-rc1

- openpower/patches/vesnin-patches/occ-p8/occ-0002-Add-temperature-sensor-support-for-CPU-cores.patch
IPMI protocol imposes limits on numbers of sensors identifiers (1 byte).
This limitation doesn't allow us to use unique temperature sensor ID for
each CPU core (4 CPU * 12 cores = 48 sensors).
Added patch makes OCC use own ID as channel label instead of using IPMI
temperature sensor ID.
Signed-off-by: Artem Senichev <a.senichev@yadro.com>
> vesnin: Add temperature sensor support for CPU cores

- openpower/package/hostboot-p8/hostboot-p8.mk
- openpower/patches/vesnin-patches/hostboot-p8/hostboot-0005-Fill-empty-sensor-id-to-reserved-id-0xFF.patch
Changes Included for package hostboot, branch master-p8:
c2471ac - Dan Crowell - 2019-01-09 - Reduce ipmi trace spam for pnor hiomap messages
6661a2d - Andrew Jeffery - 2019-01-09 - console: ast2400: Indicate SP has met configuration requirements
a47b14c - Corey Swenson - 2019-01-09 - Increase ipmi polling frequency to every 1ms
adb33e7 - Corey Swenson - 2019-01-09 - Fix lpc hard reset
26cd997 - Andrew Jeffery - 2019-01-09 - sio: Add test for availability
775f660 - Corey Swenson - 2019-01-09 - Allow larger data for TRANS_FW LPC operations
34cb7b3 - Corey Swenson - 2019-01-09 - Cleanup fixes for hiomap ipmi-pnor enabled compile
ec77327 - Nick Bofferding - 2019-01-09 - Fix shutdown race condition and task start error in IPMI SEL library
2bf43a5 - Corey Swenson - 2019-01-09 - Enable IPMI …
> op-build update for master-p8 with fix for Vesnin patch

- openpower/package/libflash/libflash.mk
libflash from skiboot v6.2
Samuel Mendoza-Jonas (2):
libflash: Restore blocklevel tests
libflash: Don't merge ECC-protected ranges
Stewart Smith (1):
libflash/file: greatly increase perf of file_erase()
> libflash from skiboot v6.2

- openpower/package/openpower-pnor/Config.in
op-build/openpower/package/openpower-pnor/Config.in:82: syntax error
op-build/openpower/package/openpower-pnor/Config.in:81: unknown option "boolean"
(cherry picked from commit 0980b48df85cc926ee0955723f034c17efcec602)
Reported-by: Michael Lim <youhour@us.ibm.com>
> 2.0.y: openpower: pnor: Fix BR2_TARGET_SKIBOOT_XZ option

- openpower/package/petitboot/63-md-raid-arrays.rules
- openpower/package/petitboot/65-md-incremental.rules
Commit 0500d1a "mdadm: move from /usr/sbin to /sbin" in Buildroot moved
the location of mdadm; update our udev scripts to reflect the change.
> petitboot: Update mdadm path

- openpower/package/petitboot/shell_config
Call 'sudo -K' on shell exit to remove cached credentials. This avoids
the case where a user could still automatically sudo after setting a
password if they had entered the shell recently.
Also explicitly set the PS1 based on the current UID so that 'su' by
default still updates the prompt.
> petitboot: Reset sudo timeout & update prompt

- openpower/package/petitboot/shell_config
If no password is set Petitboot will automatically open a shell as the
root user, and prints a message. Update this message to be more helpful
to a user if they're not aware that password authentication is
available.
> petitboot: Update login prompt message

- openpower/configs/barreleye_defconfig
- openpower/configs/firenze_defconfig
- openpower/configs/firestone_defconfig
- openpower/configs/garrison_defconfig
- openpower/configs/habanero_defconfig
- openpower/configs/openpower_mambo_defconfig
- openpower/configs/p9dsu_defconfig
- openpower/configs/palmetto_defconfig
- openpower/configs/pseries_defconfig
- openpower/configs/romulus_defconfig
- openpower/configs/vesnin_defconfig
- openpower/configs/witherspoon_defconfig
- openpower/configs/witherspoon_dev_defconfig
- openpower/configs/zaius_defconfig
- openpower/configs/zz_defconfig
Upstream release notes:
http://lists.busybox.net/pipermail/buildroot/2019-February/243960.html
https://git.buildroot.net/buildroot/plain/CHANGES?id=2018.11.3
> buildroot: Move to 2018.11.3 stable release

- ci/Dockerfile/fedora29
Rsync is needed for buildroot.
Signed-off-by: Artem Senichev <a.senichev@yadro.com>
> ci: Add rsync to fedora docker image

- README.md
- ci/Dockerfile/fedora29
- ci/Dockerfile/ubuntu1804
Update buildroot for Linux 5.0 support, LVM bug fix, localedef fix that should re-enable translations for Petitboot. Also includes 2019.02.1 security and bugfix point release.
> buildroot: 2019.02.1, Linux 5.0, LVM, make, localedef fixes

- ci/build.sh
openpower_p9_mambo_defconfig is now called opal_defconfig.
> ci: Rename defconfig in build.sh

- README.md
- op-build
The current build instructions rely on sourcing op-build-env into the
user's shell. But that assumes the user's shell is bash or sh. There's
also no reason to pollute the user's shell with op-build related
environment variables etc.
So add an op-build script, which performs the same function and
doesn't depend on what the user's shell is and is self contained. It
just uses op-build-env, which is unchanged, so should have no impact
on CI or other existing workflows.
Update the build instructions to refer to it.
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
> Add op-build script

- openpower/package/skiboot/skiboot.mk
We need to do the build with the PATH set to the host tools. Without
this change the build fails when the host lacks a dtc, as it is not in
the PATH.
> skiboot: Fix building device tree with host-dtc

- openpower/package/hostboot-binaries/hostboot_binaries.mk
This commit updates the hostboot-binaries makefile to create
separate P8 or P9 install commands based on the configuration it is
building.  This eliminates installing files that are not needed
for certain configurations.
Signed-off-by: Mike Baiocchi <mbaiocch@us.ibm.com>
> Update hostboot-binaries makefile

- openpower/package/petitboot/63-md-raid-arrays.rules
- openpower/package/petitboot/65-md-incremental.rules
[ Upstream commit fbddd4d51c41e844f6322fe08c3f1208342aa51d ]
Commit 0500d1a "mdadm: move from /usr/sbin to /sbin" in Buildroot moved
the location of mdadm; update our udev scripts to reflect the change.
Fixes: 4b51f22a943eb27a5d131bb7cc61a15b96947bb5 [2.0.y]
> [2.0.y] petitboot: Update mdadm path

- openpower/package/openpower-pnor/Config.in
- openpower/package/openpower-pnor/openpower-pnor.mk
- Add new config parameters + makefile updates to enable OCMBFW
pnor partition population
- This change is dependent on the PNOR changes (located here:
https://github.com/open-power/pnor/pull/121)
> Enable OCMBFW PNOR Partition Population in PNOR package

- .gitmodules
Upstream release notes:
http://lists.busybox.net/pipermail/buildroot/2019-June/251548.html
https://git.buildroot.net/buildroot/plain/CHANGES?id=2019.05
> buildroot: Move to 2019.05

- openpower/configs/hostboot/palmetto.config
Fix palmetto hostboot config to use PNORDD_IS_IPMI, with other config
changes to make Palmetto hostboot correctly use IPMI for hiomap.
This needs to be run with an OpenBMC configured to use hiomap.
Signed-off-by: Lei YU <mine260309@gmail.com>
> palmetto config: Use PNORDD_IS_IPMI

- openpower/configs/nicole_defconfig
- The definition of a Patches directory is pointing to something
that does not currently exist so this config fails to build
Signed-off-by: Bill Hoffa <wghoffa@us.ibm.com>
> Remove nicole config patches directory declaration

- openpower/configs/hostboot/vesnin.config
Use IPMI/HIOMAP to work with PNOR flash.
Signed-off-by: Artem Senichev <a.senichev@yadro.com>
> vesnin config: Add PNOR over HIOMAP support

- openpower/package/Config.in
- openpower/package/ocmb-explorer-fw/Config.in
- openpower/package/ocmb-explorer-fw/ocmb_explorer_fw.mk
- openpower/package/openpower-pnor/Config.in
- openpower/package/openpower-pnor/openpower-pnor.mk
- This is temporarily pointing to: https://github.com/wghoffa/test-binary-release/releases
as an example for how OCMBFW binary delivery could be done (Tagged binary image release)
- This example includes all the necessary config/makefile updates
to enable the successful binary image extraction + processing so the image is
placed in the correct PNOR partition
- This is currently dependent on a PNOR change
(https://github.com/open-power/pnor/pull/122) so it won't compile without
pulling this change in
Signed-off-by: Bill Hoffa <wghoffa@us.ibm.com>
> Create Build Infrastructure for OCMBFW Image Delivery

- openpower/package/ocmb-explorer-fw/Config.in
This package isn't currently used on any upstream OpenPOWER platforms,
so default to n. Platforms can enable it through their configs instead.
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
> package/ocmb-explorer-fw: default to n

- openpower/package/openpower-pnor/openpower-pnor.mk
A backport of a fix in hostboot requires a bigger HBI partition so
moving up to a more recent level of the pnor package that includes
a bump.
> Bump up version for openpower-pnor package

- openpower/package/openpower-pnor/openpower-pnor.mk
Previously we were using the * wildcard to lookup files to copy
over for debug data. This breaks when there are multiple versions
of a given package built in the output/build directory. This commit
will make the openpower-pnor.mk files use the build root env vars
(BR2_..) to make sure we just attempt to copy files from the current
version we are using.
> Update openpower-pnor makefile to use BR2_ version vars

- README.md
A default Fedora29 ppc64el install is missing a few dependent packages in order to be able to build op-build
> Documentation: Update Readme.md for Fedora installs

- openpower/scripts/firmware-whitelist
The 5.2 kernel requires version 7.13.11.0 of the Broadcom bnx2x
firmware. This can be found in the latest linux-firmware package.
A corresponding change has been made to the firmware whitelist script so
the new version is included.
This fixes the following symptoms:
bnx2x 0003:01:00.0: Direct firmware load for bnx2x/bnx2x-e2-7.13.11.0.fw failed with error -2
> buildroot: Update to pick up new linux-firmware

- openpower/package/openpower-pnor/openpower-pnor.mk
open-power/hostboot commit 845fb44 creates a edited XML
PNOR layout with edited offsets. For ease of debugging,
this file is placed inside of host_fw_debug.tar.
> Place Created XML File in HB Debug tar

- openpower/package/libflash/libflash.mk
We have merged 100+ pathes after v6.4. I didn't realize that we have
separate package for libflash and missed to update :-(
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
> libflash: skiboot v6.5-61-g66ab3cbd

- openpower/package/ppe42-binutils/ppe42-binutils.mk
- openpower/package/ppe42-gcc/ppe42-gcc.mk
(obsoletes PR #3162)
Updates to ppe42-gcc:
* Backport fix for search_line_fast on POWER/ALTIVEC (Klaus Kiwi on Oct 29)
* PPE42X Frame pointer not set/restored (Douglas Gilbert on Aug 22)
* PPE42X (Douglas Gilbert on Jun 15, 2018)
* Stack enhancements (Douglas Gilbert on May 8, 2018)
Update to ppe42-binutils:
* New PPE instructions for P10 (Douglas Gilbert on Jun 9, 2018)
> Update ppe42 toolchain with fixes and enhancements (obsoletes PR #3162)

- openpower/configs/mihawk_defconfig
- openpower/patches/mihawk-patches/openpower-pnor/openpower-pnor-20191118-change-kernel-size-to-24MB.patch
Add openpower-pnor patch file to increase Bootloader Kernel partition size to 20MB for built-in RAID tool support
Signed-off-by: Joy Chu <joy_chu@wistron.com>
> Modify kernel partition size for some built-in tools

- openpower/package/libflash/Config.in
- openpower/package/libflash/libflash.mk
libflash code sits inside skiboot source tree. Use SKIBOOT_VERSION
instead of having separate version.
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
> openpower/libflash: Use SKIBOOT_VERSION

- README.md
Signed-off-by: Stewart Smith <stewart@flamingspork.com>
> Update README.md for Fedora 31 build-deps

- openpower/package/petitboot/petitboot.hash
- openpower/package/petitboot/petitboot.mk
This change bumps us up to petitboot v1.12, which contains a pre-boot
check feature for ultravisor enabled kernels, support for kexec file,
and the display of secure and trusted boot state.
Jeremy Kerr (10):
lib/pb-protocol: fix ordering of system info length calculation
lib/types: consolidate struct system_info layout with serialised version
protocol,types: Add secure & trusted boot state to system info
discover/powerpc: detect secureboot enforcing mode
ui/ncurses: Add secure & trusted boot status
discover/boot: add support for `kexec -s` for kexec_file_load
discover/boot: unify verification failure messages
Remove unused 's' file
docker: build petitboot outside of the source dir
test/parser: Add rhel8 test data to check_DATA
Maxiwell S. Garcia (4):
configure: Add libelf as a requirement …
> petitboot: Update to v1.12

- openpower/package/openpower-pnor-util/openpower-pnor-util.mk
- openpower/package/openpower-pnor/openpower-pnor.mk
The config name is generally speaking the name of the system. This
name will be added to the manifest file in the squashfs tarball to
check against the name of the system, in order to log an error if
the machine names don't match, since this might indicate that the
wrong image file is being used for that system.
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
> openpower-pnor: Add config name to manifest

- openpower/package/libflash/libflash.mk
LIBFLASH_VERSION is not set correctly when using a
BR2_SKIBOOT_CUSTOM_GIT, causing the package to
not be downloaded.
Additionally, add skiboot as a build-time dependency
Supersedes #3451
> libflash.mk: fix version and add dependencies

- op-build-env
There are parts of the firmware that rely on English/C locale for some generated
content, for example testfapi2.C and testfapi2_rt.C in Hostboot are created during
the build and they are created incorrectly when the build runs in cs_CZ.UTF-8 locale.
Signed-off-by: Dan Horák <dan@danny.cz>
Fixes: https://lists.ozlabs.org/pipermail/openpower-firmware/2019-December/000435.html
> run build in defined locale

- openpower/package/petitboot/petitboot.mk
Petitboot 1.7.6 contains significant fixes versus 1.7.5, most notably in
the area of grub2 config parsing that some Distros are now using. This
update should prevent Petitboot from trapping or not finding
configurations on Red Hat Enterprise Linux and OpenShift installations.
Update summary:
----------------------------------------------------------------
Brandon Bergren (1):
Fix pb-discover segfaults caused by list corruption.
Brett Grandbois (3):
discover/grub: Add cmdline signature support for BLS entries
lib/file: remove mkstemp umask in copy_file_secure_dest
discover/boot: abort kexec on any error from validation
Geoff Levand (1):
lib/talloc: Fix TALLOC_ABORT
Javier Martinez Canillas (10):
discover/grub: Add blscfg command support to parse BootLoaderSpec files
discover/grub: Allow to …
> Update Petitboot to 1.7.6

- openpower/package/openpower-pnor/openpower-pnor.mk
BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE is not always defined (i.e., when
using a Custom Repo, Latest version etc). However,
BR2_LINUX_KERNEL_VERSION will always default to whatever kernel version
we are using.
This fixes building openpower-pnor when not using a Kernel Custom
version.
> openpower-pnor.mk: Use correct kernel version macro

- openpower/configs/barreleye_defconfig
- openpower/configs/blackbird_defconfig
- openpower/configs/firenze_defconfig
- openpower/configs/firestone_defconfig
- openpower/configs/garrison_defconfig
- openpower/configs/habanero_defconfig
- openpower/configs/mihawk_defconfig
- openpower/configs/nicole_defconfig
- openpower/configs/opal_defconfig
- openpower/configs/p8dtu_defconfig
- openpower/configs/p9dsu_defconfig
- openpower/configs/palmetto_defconfig
- openpower/configs/pseries_defconfig
- openpower/configs/romulus_defconfig
- openpower/configs/vesnin_defconfig
- openpower/configs/witherspoon_defconfig
- openpower/configs/zaius_defconfig
- openpower/configs/zz_defconfig
This adds support for 5.5 kernels to buildroot, but updates the
defconfigs in order to continue to use the 5.4 kernel for now.
> buildroot: Support 5.5 kernels

- ci/build-all-defconfigs.sh
Fix dumb typo in the hash function deciding if a new SDK should be built
or not.
> ci: Fix SDK hash function

- openpower/package/openpower-pnor/openpower-pnor.mk
Use the correct <pkg>_VERSION variables for packages, instead of the
ones defined in _defconfig.
Fixes build in situations where the <pkg>_VERSION variable is overriden
(i.e., when using <pkg>_OVERRIDE_SRCDIR) since the build directory
always depends on this variable, not the one defined in the _defconfig.
> openpower-pnor.mk: use correct version vars

- openpower/package/openpower-pnor/openpower-pnor.mk
- Add the ocmbfw version information to the
version pnor partition for machine types that
use the ocmb
Signed-off-by: Bill Hoffa <wghoffa@us.ibm.com>
> Add OCMBFW Version to Version PNOR Partition

- openpower/patches/mihawk-patches/openpower-pnor/openpower-pnor-20200618-change-kernel-size-to-24MB.patch
Mihawk patch was failing after merging skiboot partition size patch - https://github.com/open-power/pnor/pull/134
This patch fixes the mihawk patch - openpower/patches/mihawk-patches
to apply correctly now.
Thanks & Regards,
- Nayna
> patches/mihawk: adjust patch to apply on top of skiboot-increasing patch

- ci/Dockerfile/ubuntu2004
Commit 34b9a2dc7 moved the CI to Ubuntu 20.04 Focal but was
still depending on python-matplotlib and python-numpy for it's
'release' steps (where make legal-info and graphs are built),
while those are no longer available in Focal.
Replace them for python3-matplotlib and python3-scipy, also
adjusting python to python3-is-python so that things work
again.
Signed-off-by: Klaus Heinrich Kiwi <klaus@linux.bnet.ibm.com>
----------
I missed this since the Ci was skipping silently for Ubuntu 20.04 containers. That should be fixed as well.
Fixes #3808
> Fixes package list for Ubuntu 20.04 CI

- openpower/patches/mihawk-patches/hostboot/hostboot-20200728-changed-Delay-registers-and-RD-VERF-registers-values.patch
Samsung 16G DIMM M393A2K40DB2-CTD on Mihawk was showing
the TC2 result could not be pass completely in the 2DPC configuration.
The IBM team suggested a new setting to increase the delay register
and decrease RD_VREF register. Wistron conducts a series of research and
optimization to achieve the best settings. The ultimate motive is to
center the eye.
Samsung 16G DIMM M393A2K40DB2-CTD & M393A2K40BB2-CTD have
been tested memory qual TC2 for 1DPC & 2DPC configuration on Mihawk to
make sure the settings are compatible. However, the new settings should
not be used on platforms other than Mihawk.
Signed-off-by: Nichole Wang <Nichole_Wang@wistron.com>
> Modify the delay and RD_VREF register to solve the memory qual fail

- README.md
POWER8 targets were removed by commit 40f804058414. Use a POWER9
one for the example.
> README: Update "Building an image" example

- README.md
Add perl FindBin, English, Time dependencies for Fedora
Otherwise host-libopenssl fails to build, saying ppc64el isn't
supported, but a couple of lines up, hints at the perl module.
Hostboot also needs the English and Time::localtime modules.
This should also be cherry-picked to v2.6 at least.
> Add perl dependencies for building on Fedora 33

- openpower/patches/mihawk-patches/openpower-pnor/0001-Increase-BOOTKERNEL-to-24MiB.patch
This fixes the Mihawk build (Github issue #4069) that was
introduced with a0f34ce
Fixes: a0f34ce 'op-build update 11-20-2020'
> mihawk: Refresh 24MB BOOTKERNEL patch

- openpower/package/ppe42-gcc/ppe42-gcc.mk
Increase the version of the ppe42-gcc package to the latest version in
the repo so that all of the fixes are picked up.
> Increase the Version of ppe42-gcc

- openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
- openpower/package/openpower-pnor/openpower-pnor.mk
This commit removes the targeting_RW_binary_source parameter from
update_image.pl, since the parameter is no longer used.
> Remove targeting_RW_binary_source Parameter

- openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
Adding files hbicore.syms and hbotStringFile to the PNOR scratch dir so LID files can be created from these files. hbicore.syms will be LID file 81e00686 and hbotStringFile file will be LID file 81e00685.
RTC: 295909
> Adding files hbicore.syms and hbotStringFile to the PNOR scratch dir

- openpower/package/skiboot/Config.in
By defaulting to BR2_SKIBOOT_CUSTOM_GIT, the custom URL overrode the
default URL for the skiboot repo, forcing the need to have a defualt
custom URL too.
This which was used during internal p10 bring up to force the URL to an
internal repository. There's no need to do it now, and github.com is
moving away from the git:// protocol, so remove the custom default so we
get buildroot's normal URL construction from SKIBOOT_SITE in skiboot.mk.
Overriding the URL can still be done via the defconfig where it is
useful.
> skiboot: Use open-opwer/skiboot.git again

- openpower/package/ppe42-gcc/0001-reload-Change-to-type-of-x_spill_indirect_levels.patch
When building with GCC 11, which defaults to C++17:
../.././gcc/reload1.c: In function ‘void init_reload()’:
../.././gcc/reload1.c:89:24: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17
89 |   (this_target_reload->x_spill_indirect_levels)
|   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
../.././gcc/reload1.c:444:7: note: in expansion of macro ‘spill_indirect_levels’
444 |       spill_indirect_levels++;
|       ^~~~~~~~~~~~~~~~~~~~~
Make the same fix as was made upstream:
https://github.com/gcc-mirror/gcc/commit/d57c99458933a21fdf94f508191f145ad8d5ec58
> ppe42-gcc: Add build fix

- openpower/package/sbe-p10/sbe-p10.mk
RH7 has /bin/python defined in it's environment whereas RH8 will not.  RH8
will not have a default of /bin/python but will only have /bin/python2 and
/bin/python3 defined.
Considering that for RH7 /bin/python is just a symbolic link to /bin/python2,
making this change to explicitly call python2 will have no detrimental affects
for compiling SBE on RH7 but will position the compiling of the SBE code on
RH8 for success.
Signed-off-by: Roland Veloz <rveloz@us.ibm.com>
> RH8: Update the call to python to be python2 in migration effort to Red Hat 8

- openpower/package/sbe/sbe.mk
Update the call from python to python2 in migration effort to Red Hat 8.
RH7 has /bin/python defined in it's environment whereas RH8 will not. RH8
will not have a default of /bin/python but will only have /bin/python2 and
/bin/python3 defined.
Considering that for RH7, /bin/python is just a symbolic link to /bin/python2,
making this change to explicitly call python2 will have no detrimental affect.
Signed-off-by: Roland Veloz <rveloz@us.ibm.com>
> P9: Migration effort to Red Hat 8

- openpower/package/occ-p10/occ-p10.mk
- openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
Adding occStringFile so that a lid file can be created.
Lid: 81e00687
CQ: SW554564
Signed-off-by: Chris Cain <cjcain@us.ibm.com>
> Add occStringFile to PNOR scratch dir

- openpower/package/sbe-p10/sbe-p10.mk
For Red Hat 8, there will be no default /bin/python only /bin/python2
and /bin/python3.  For Red Hat 7 /bin/python is just a symlink to python2,
therefore all calls to python need to be changed to python2 which is
safe to do.
Signed-off-by: Roland Veloz <rveloz@us.ibm.com>
> SBE-P10: Update the call python to python2 for Red Hat 8 migration

- openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
PNOR SPD partition commit was erroneously merged into release-fw-1030 branch. This commit reverts the PNOR repo back to the previous commit.
> Revert PNOR SPD Commit

- openpower/package/rainier-2u-xml/rainier-2u-xml.mk
Sample template for Planar SPD building.
This sample is built using the rainier-2u-xml.mk,
to copy for Planar builds change related prefixes
of RAINIER_2U_XML_ to new XML naming scheme.
PFHB-5
Signed-off-by: Deb McLemore <debmc@us.ibm.com>
> Hostboot Add Building of Planar SPD

- openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
Need to chain the multiple shell commands together with && for create_pnor_image.pl so that any failures in called scripts (e.g. die, etc) are properly caught and surfaced.
Without chaining the shell commands together with && the success of the operation to create_pnor_image.pl may fail silently.
Exposure to this type of problem was detected with the newly introduced buildSPDImages.pl script which was stress tested by overflowing the PSPD image which is built outside the space constraints of the PNOR logic (checkSpaceConstraints).
Signed-off-by: Deb McLemore <debmc@us.ibm.com>
> OP-BUILD Failure Hardening

- openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
Commit adds support for parsing of traces captured by power management engines. TrexStringFiles are copied from build directory to PNOR scratch directory as LID.
> p10 Hcode: Added support for trace parsing in error log.

- openpower/package/openpower-pnor-p10/openpower-pnor-p10.mk
Reverts open-power/op-build#5263
This change breaks ppc compiles because of the hardcoded "images_x86_64" path.
PNOR UBI image at /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-p10-public-github-619/CONFIG/p10ebmc/OS/ubuntu/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/pnor.RAINIER_2U_XML/RAINIER_2U_XML.pnor.ubi.mtd
/usr/bin/install: cannot stat '/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-p10-public-github-619/CONFIG/p10ebmc/OS/ubuntu/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../build/hcode-p10-*opmst10/output/images_x86_64/qme_p10dd20/trexStringFile': No such file or directory
This is what exists in the ppc compile.  I think the generic …
> Revert "p10 Hcode: Added support for trace parsing in error log."

- openpower/package/petitboot/petitboot.hash
- openpower/package/petitboot/petitboot.mk
Changes since v1.12:
discover/udev.c: Added warning for duplicate FS UUIDs in system status log
discover/grub2: Add the '-e' test support
discover: Allow for empty paths
discover/platform-powerpc: Fix build warning
ncurses/nc-menu: Remove stray declaration
> petitboot: Move to v1.13 release

- .gitmodules
- README.md
- openpower/configs/blackbird_defconfig
- openpower/configs/mihawk_defconfig
- openpower/configs/mowgli_defconfig
- openpower/configs/nicole_defconfig
- openpower/configs/opal_defconfig
- openpower/configs/p9dsu_defconfig
- openpower/configs/romulus_defconfig
- openpower/configs/swift_defconfig
- openpower/configs/witherspoon_defconfig
- openpower/configs/zaius_defconfig
- openpower/configs/zz_defconfig
Reverts open-power/op-build#5629
It is totally my mistake for not running `git submodule update` which means the `buildroot` is still pointing to the `2021.02-op-build`.
I would like to revert that changes and will work on a [new PR](https://github.com/open-power/op-build/pull/5679) to bump buildroot to `2023.02`.
cc @IlyaSmirnov91
> Revert "buildroot: Bump to version 2023.02-op-build"

- openpower/package/sbe-odyssey/sbe-odyssey.mk
Using the 'sbe workon' command spawns a new shell which can have some bad side effects to some of the automated build scripts. This change switches over to using an inline script for the build instead.
> Adjust Odyssey SBE Build Command

- openpower/package/sbe-odyssey/sbe-odyssey.mk
- openpower/package/sbe-p10/sbe-p10.mk
This commit converts the buildroot variable BR2_OPENPOWER_SIGNED_SECURITY_VERSION into a local environment variable in specific spots of the sbe-p10 and sbe-odyssey makefiles.  This ensures that those packages are built with the same value as the rest of the build.
Resolves #5882
> Add BR2_OPENPOWER_SIGNED_SECURITY_VERSION into sbe makefiles

- openpower/package/sbe-odyssey/sbe-odyssey.mk
We were sending the output to /dev/null for some reason
> Do not hide output from sbe build

- openpower/package/petitboot/petitboot.hash
- openpower/package/petitboot/petitboot.mk
Update to the latest petitboot for bug fixes. Most notably, it fixes a bootloader config parsing issue causing the discovery process to crash when it encounters installations of recent Fedora CoreOS.
> petitboot: Update to v1.15

- openpower/package/sbe-odyssey/sbe-odyssey.mk
-This is required so that external users can access SBE tools for debugging
> Copy SBE Tools to staging dir

- openpower/package/sbe-p10/sbe-p10.mk
This commit converts the buildroot variable BR2_OPENPOWER_SIGNED_SECURITY_VERSION into a local environment variable in a specific spot of the sbe-p10 makefile.  This ensures that the sbe-p10 package is built with the same value as the rest of the build.
> Add BR2_OPENPOWER_SIGNED_SECURITY_VERSION into sbe-p10 makefile

- openpower/package/openpower-pnor-p11/openpower-pnor-p11.mk
This commit passes in common directories to build the SBE and OCMBFW PNOR sections/lids into the PNOR update_image.pl script.
These common directories can then be used to just build the SBE and OCMBFW one time and share with all of the system-specific directories.
This commit also picks up the latest main-p11 pnor commit to support these new directories.
> Add support for common SBE and OCMBFW PNOR sections

- openpower/package/openpower-pnor-p11/openpower-pnor-p11.mk
-Sets env var SALT_FOR_HASH_PAGE_TABLES so
hostboot picks this up and is able to use the
same value for each pass generating binaries
> Added consistent salt for HB HPT generation
